export interface PathLesson {
  title: string;
  type: 'speaking' | 'listening' | 'writing' | 'grammar' | 'vocabulary' | 'flashcards' | 'exam' | 'roleplay';
  href: string;
  icon: string;
  description: string;
}

export interface PathNode {
  id: string;
  stageTitle: string;
  targetScore: string;
  description: string;
  skills: string[];
  expReward: number;
  coinReward: number;
  lessons: PathLesson[];
  isMockTest?: boolean;
}

export interface LearningPath {
  id: string;
  examCode: string;
  title: string;
  badge: string;
  icon: string;
  color: string;
  badgeBg: string;
  badgeText: string;
  description: string;
  targetScores: string[];
  nodes: PathNode[];
}

export const LEARNING_PATHS: Record<string, LearningPath> = {
  toeic: {
    id: 'toeic',
    examCode: 'toeic',
    title: 'Lộ Trình TOEIC Quốc Tế (Part 1 - Part 7)',
    badge: 'Mục Tiêu 450 - 800+ TOEIC',
    icon: '🎯',
    color: 'from-amber-500 to-orange-500',
    badgeBg: 'bg-amber-100',
    badgeText: 'text-amber-900 border-amber-300',
    description: 'Chinh phục chứng chỉ TOEIC giao tiếp & môi trường doanh nghiệp quốc tế qua 4 mốc chuẩn hoá.',
    targetScores: ['350+ Nền Tảng', '500+ Phản Xạ', '650+ Bứt Phá', '800+ Thi Thử'],
    nodes: [
      {
        id: 'toeic-node-1',
        stageTitle: 'Mốc 1: Từ Vựng & Ngữ Pháp Nền Tảng TOEIC (Target 350+)',
        targetScore: 'TOEIC 350+',
        description: 'Chuẩn hoá 300 từ vựng văn phòng thường gặp trong Part 1 & Part 2. Nắm chắc 4 thì cơ bản với Ngữ Pháp Lego.',
        skills: ['Từ Vựng Văn Phòng', 'Thì Hiện Tại & Quá Khứ', 'Phân Biệt Hình Ảnh Part 1'],
        expReward: 50,
        coinReward: 30,
        lessons: [
          {
            title: 'Học Ngữ Pháp Lego: Công Tắc Chuyển Thì Văn Phòng',
            type: 'grammar',
            href: '/grammar',
            icon: '🧱',
            description: 'Lắp ghép 4 khối Lego: Chủ ngữ, Động từ, Tân ngữ và Thời gian.',
          },
          {
            title: 'Lật Flashcards 3D: 100 Từ Vựng TOEIC Căn Bản',
            type: 'flashcards',
            href: '/flashcards',
            icon: '🃏',
            description: 'Ôn tập lặp lại ngắt quãng SRS từ vựng Part 1 & Part 2.',
          },
          {
            title: 'Luyện Nghe Tốc Độ 0.75x: Đội Nhóm Văn Phòng',
            type: 'listening',
            href: '/practice/listening',
            icon: '🎧',
            description: 'Luyện nghe câu hỏi & câu trả lời Part 2 thường gặp.',
          },
        ],
      },
      {
        id: 'toeic-node-2',
        stageTitle: 'Mốc 2: Phản Xạ Nghe Hiểu & Đọc Đoạn Văn Short (Target 500+)',
        targetScore: 'TOEIC 500+',
        description: 'Tăng tốc phản xạ nghe đàm thoại ngắn (Part 3) và chiến thuật giải bài đọc điền từ Part 5 & 6.',
        skills: ['Hội Thoại Part 3', 'Chiến Thuật Part 5', 'Giao Tiếp Email'],
        expReward: 75,
        coinReward: 45,
        lessons: [
          {
            title: 'Luyện Nói Voice AI: Trình Bày Công Việc Hàng Ngày',
            type: 'speaking',
            href: '/practice/speaking',
            icon: '🎙️',
            description: 'Phát âm chuẩn IPA câu trả lời phỏng vấn & trao đổi công sở.',
          },
          {
            title: 'Luyện Viết Phản Xạ: Viết Email Trả Lời Khách Hàng',
            type: 'writing',
            href: '/practice/writing',
            icon: '🖊️',
            description: 'Lắp ghép khối từ thành câu email hoàn chỉnh.',
          },
          {
            title: 'Kho Từ Vựng: 50 Collocations TOEIC Bắt Buộc Nhớ',
            type: 'vocabulary',
            href: '/vocabulary',
            icon: '✨',
            description: 'Cụm từ đi cùng nhau cực kỳ hay gặp trong bài thi TOEIC.',
          },
        ],
      },
      {
        id: 'toeic-node-3',
        stageTitle: 'Mốc 3: Bứt Phá Điểm Số & Bẫy Bẫy Đề Thi (Target 650+)',
        targetScore: 'TOEIC 650+',
        description: 'Nhận diện bẫy phát âm đồng âm Part 2, làm quen với bài đọc nhiều đoạn (Double/Triple Passages) Part 7.',
        skills: ['Bẫy Đồng Âm Part 2', 'Bài Đọc Bài Kép Part 7', 'Thương Lượng Hợp Đồng'],
        expReward: 100,
        coinReward: 60,
        lessons: [
          {
            title: 'Đóng Vai Daily Scrum: Thương Lượng & Báo Cáo',
            type: 'roleplay',
            href: '/practice/roleplay',
            icon: '🎮',
            description: 'Mô phỏng đàm thoại công việc với đồng nghiệp bản xứ.',
          },
          {
            title: 'Luyện Nghe Tốc Đội Bản Xứ 1.0x: Thuyết Trình Bài Phát Thuyết',
            type: 'listening',
            href: '/practice/listening',
            icon: '🎧',
            description: 'Phần nghe Part 4 với tốc độ nói tự nhiên của người bản xứ.',
          },
          {
            title: 'Sổ Từ Bookmark: Ôn Tập Các Từ Đã Bôi Đen Tra Từ',
            type: 'vocabulary',
            href: '/bookmarks',
            icon: '🔖',
            description: 'Củng cố các từ khó bạn đã lưu khi đọc báo hay tra từ điển.',
          },
        ],
      },
      {
        id: 'toeic-node-4',
        stageTitle: 'Mốc Cuối: THI THỬ THỰC CHIẾN MOCK TEST (Target 800+)',
        targetScore: 'MOCK TEST 800+',
        description: 'Bài kiểm tra tổng hợp bấm giờ chuẩn CEFR. Đánh giá chính xác điểm số và nhận chứng chỉ hoàn thành.',
        skills: ['Thi Bấm Giờ', 'Chấm Điểm Tự Động', 'Nhận Huy Hiệu TOEIC Master'],
        expReward: 150,
        coinReward: 100,
        isMockTest: true,
        lessons: [
          {
            title: 'Vào Trung Tâm Thi Thử TOEIC Trực Tuyến',
            type: 'exam',
            href: '/exam?category=toeic',
            icon: '🏆',
            description: 'Làm bài thi thử 200 câu bấm giờ, nhận kết quả và phân tích chi tiết.',
          },
        ],
      },
    ],
  },

  vstep: {
    id: 'vstep',
    examCode: 'vstep',
    title: 'Lộ Trình VSTEP Độc Quyền (B1 - B2 - C1)',
    badge: 'Chuẩn Khung 6 Bậc BGD',
    icon: '🇻🇳',
    color: 'from-emerald-500 to-teal-600',
    badgeBg: 'bg-emerald-100',
    badgeText: 'text-emerald-900 border-emerald-300',
    description: 'Chinh phục kỳ thi năng lực ngoại ngữ VSTEP B1, B2, C1 phục vụ tốt nghiệp, công chức & học cao học.',
    targetScores: ['VSTEP B1 Sơ Cấp', 'VSTEP B2 Trung Cấp', 'VSTEP C1 Cao Cấp', 'Thi Thử VSTEP'],
    nodes: [
      {
        id: 'vstep-node-1',
        stageTitle: 'Mốc 1: Cốt Lõi VSTEP B1 (Đạt 4.0 - 5.5 Điểm)',
        targetScore: 'VSTEP B1',
        description: 'Xây dựng từ vựng 10 chủ đề đời sống VSTEP. Luyện viết thư cá nhân / email xin việc Task 1.',
        skills: ['Viết Thư Task 1', 'Nghe Đàm Thoại Ngắn', 'Từ Vựng Đời Sống'],
        expReward: 50,
        coinReward: 30,
        lessons: [
          {
            title: 'Luyện Viết Phản Xạ: Bố Cục Thư Cá Nhân VSTEP Task 1',
            type: 'writing',
            href: '/practice/writing',
            icon: '🖊️',
            description: 'Thực hành ghép các mẫu câu mở đầu và kết thúc thư.',
          },
          {
            title: 'Học Ngữ Pháp Lego: Câu Cấu Trúc Đặt Điểm B1',
            type: 'grammar',
            href: '/grammar',
            icon: '🧱',
            description: 'Các mẫu câu so sánh, câu điều kiện loại 1 & 2.',
          },
        ],
      },
      {
        id: 'vstep-node-2',
        stageTitle: 'Mốc 2: Nâng Cấp VSTEP B2 (Đạt 6.0 - 7.5 Điểm)',
        targetScore: 'VSTEP B2',
        description: 'Luyện nói 3 phần VSTEP Speaking: Tương tác xã hội, Thảo luận giải pháp, Phát triển chủ đề.',
        skills: ['Speaking 3 Parts', 'Viết Luận Task 2', 'Đọc Hiểu Báo Chí'],
        expReward: 80,
        coinReward: 50,
        lessons: [
          {
            title: 'Luyện Nói Voice AI: Trả Lời 3 Phần VSTEP Speaking',
            type: 'speaking',
            href: '/practice/speaking',
            icon: '🎙️',
            description: 'AI chấm điểm độ trôi chảy, từ vựng và ngữ pháp phát âm.',
          },
          {
            title: 'Luyện Nghe Tốc Độ: Nghe Bài Bài Giảng Học Thuật VSTEP',
            type: 'listening',
            href: '/practice/listening',
            icon: '🎧',
            description: 'Luyện kỹ năng bắt từ khóa (Keywords) trong bài nghe dài.',
          },
        ],
      },
      {
        id: 'vstep-node-3',
        stageTitle: 'Mốc 3: Chuyên Sâu VSTEP C1 (Đạt 8.0 - 10.0 Điểm)',
        targetScore: 'VSTEP C1',
        description: 'Luyện viết luận phản biện Task 2, phân tích từ vựng academic cao cấp.',
        skills: ['Luận Phản Biện Task 2', 'Academic Vocabulary', 'Nghe Bài Nói Chuyện Chuyên Gia'],
        expReward: 110,
        coinReward: 70,
        lessons: [
          {
            title: 'Bách Khoa Từ Điển Cambridge: Tra Cứu Từ C1 Academic',
            type: 'vocabulary',
            href: '/encyclopedia',
            icon: '📚',
            description: 'Tra phiên âm IPA chuẩn mực & câu ví dụ ngữ cảnh cao cấp.',
          },
          {
            title: 'Đóng Vai Kịch Bản: Tranh Luận & Bảo Vệ Quan Điểm',
            type: 'roleplay',
            href: '/practice/roleplay',
            icon: '🎮',
            description: 'Phản xạ đưa ra lập luận và phản bác ý kiến.',
          },
        ],
      },
      {
        id: 'vstep-node-4',
        stageTitle: 'Mốc Cuối: THI THỬ VSTEP FULL SKILLS (B1 - B2 - C1)',
        targetScore: 'MOCK TEST VSTEP',
        description: 'Thi thử đề VSTEP chuẩn cấu trúc Bộ Giáo Dục & Đào Tạo. Nhận phân tích chi tiết.',
        skills: ['Thi Bấm Giờ VSTEP', 'Đánh Giá 4 Kỹ Năng', 'Cấp Chứng Nhận VSTEP'],
        expReward: 150,
        coinReward: 100,
        isMockTest: true,
        lessons: [
          {
            title: 'Bắt Đầu Bài Thi Thử VSTEP Trực Tuyến',
            type: 'exam',
            href: '/exam?category=vstep',
            icon: '🏆',
            description: 'Vào trung tâm khảo thí làm bài thi VSTEP bấm giờ.',
          },
        ],
      },
    ],
  },

  ielts: {
    id: 'ielts',
    examCode: 'ielts',
    title: 'Lộ Trình IELTS Academic & General (5.5 - 7.5+)',
    badge: 'Mục Tiêu Band 5.5 - 7.5+',
    icon: '🇬🇧',
    color: 'from-sky-500 to-blue-600',
    badgeBg: 'bg-sky-100',
    badgeText: 'text-sky-900 border-sky-300',
    description: 'Chiến thuật nâng Band điểm IELTS toàn diện cho du học, định cư & phát triển sự nghiệp.',
    targetScores: ['IELTS 5.5 Foundation', 'IELTS 6.5 Target', 'IELTS 7.5+ Master', 'Thi Thử IELTS'],
    nodes: [
      {
        id: 'ielts-node-1',
        stageTitle: 'Mốc 1: Xây Nền IELTS Band 5.5 (Foundation)',
        targetScore: 'IELTS 5.5',
        description: 'Tăng tốc từ vựng Collocations, phương pháp Paraphrasing từ đồng nghĩa cho Listening & Reading.',
        skills: ['Paraphrasing', 'IELTS Topic Vocabulary', 'Phát Âm Chuẩn IPA'],
        expReward: 60,
        coinReward: 40,
        lessons: [
          {
            title: 'Lật Flashcards 3D: 200 Từ Vựng IELTS Topic Thông Dụng',
            type: 'flashcards',
            href: '/flashcards',
            icon: '🃏',
            description: 'Thuộc lòng từ vựng Education, Environment, Technology.',
          },
          {
            title: 'Luyện Nói Voice AI: IELTS Speaking Part 1 Warm-up',
            type: 'speaking',
            href: '/practice/speaking',
            icon: '🎙️',
            description: 'Luyện nói tự nhiên các chủ đề bản thân & sở thích.',
          },
        ],
      },
      {
        id: 'ielts-node-2',
        stageTitle: 'Mốc 2: Bứt Phá IELTS Band 6.5 (Target Standard)',
        targetScore: 'IELTS 6.5',
        description: 'Chiến thuật IELTS Writing Task 1 (Mô tả biểu đồ) và Speaking Part 2 (Thuyết trình cue card).',
        skills: ['Writing Task 1', 'Speaking Part 2 Cue Card', 'Listening Section 3'],
        expReward: 90,
        coinReward: 60,
        lessons: [
          {
            title: 'Luyện Viết Phản Xạ: Viết Mô Tả Biểu Đồ Writing Task 1',
            type: 'writing',
            href: '/practice/writing',
            icon: '🖊️',
            description: 'Ghép từ nối Cohesion & Coherence cho đoạn văn.',
          },
          {
            title: 'Luyện Nghe Tốc Độ: Nghe Hội Thoại Nhóm Section 3',
            type: 'listening',
            href: '/practice/listening',
            icon: '🎧',
            description: 'Luyện nghe thảo luận sinh viên & giảng viên đại học.',
          },
        ],
      },
      {
        id: 'ielts-node-3',
        stageTitle: 'Mốc 3: Làm Chủ IELTS Band 7.5+ (Mastery)',
        targetScore: 'IELTS 7.5+',
        description: 'Writing Task 2 Essay nâng cao, Speaking Part 3 thảo luận chuyên sâu và Reading Passage 3.',
        skills: ['Writing Task 2 Essay', 'Speaking Part 3 Abstract Discussion', 'Reading Passage 3'],
        expReward: 120,
        coinReward: 80,
        lessons: [
          {
            title: 'Bách Khoa Cambridge: Tra Cứu Từ Vựng Band 8.0+',
            type: 'vocabulary',
            href: '/encyclopedia',
            icon: '📚',
            description: 'Tra nghĩa chính xác và các ví dụ nâng cao.',
          },
          {
            title: 'Đóng Vai Scrum & Pitching: Phản Xạ Nói IELTS Part 3',
            type: 'roleplay',
            href: '/practice/roleplay',
            icon: '🎮',
            description: 'Rèn luyện phản xạ lập luận và tư duy logic tiếng Anh.',
          },
        ],
      },
      {
        id: 'ielts-node-4',
        stageTitle: 'Mốc Cuối: THI THỬ IELTS FULL MOCK TEST',
        targetScore: 'MOCK TEST IELTS',
        description: 'Đề thi thử IELTS chuẩn format thực tế. Bấm giờ và chấm điểm tự động.',
        skills: ['Thi Bấm Giờ IELTS', 'Đánh Giá Band Score', 'Phân Tích Chi Tiết Lỗi'],
        expReward: 160,
        coinReward: 100,
        isMockTest: true,
        lessons: [
          {
            title: 'Vào Phòng Thi Thử IELTS Trực Tuyến',
            type: 'exam',
            href: '/exam?category=ielts',
            icon: '🏆',
            description: 'Thực hiện bài kiểm tra IELTS bấm giờ.',
          },
        ],
      },
    ],
  },

  toefl: {
    id: 'toefl',
    examCode: 'toefl',
    title: 'Lộ Trình TOEFL iBT Quốc Tế (60 - 100+)',
    badge: 'Mục Tiêu 60 - 100+ TOEFL',
    icon: '🇺🇸',
    color: 'from-purple-500 to-indigo-600',
    badgeBg: 'bg-purple-100',
    badgeText: 'text-purple-900 border-purple-300',
    description: 'Chương trình luyện thi TOEFL iBT chuẩn giọng US Campus dành cho du học Mỹ & học thuật cao cấp.',
    targetScores: ['TOEFL 60+ Starter', 'TOEFL 80+ Target', 'TOEFL 100+ Master', 'Thi Thử TOEFL'],
    nodes: [
      {
        id: 'toefl-node-1',
        stageTitle: 'Mốc 1: Căn Bản TOEFL iBT Campus (Target 60+)',
        targetScore: 'TOEFL 60+',
        description: 'Làm quen với giọng phát âm Mỹ (American Accent) và từ vựng đời sống sinh viên đại học Mỹ.',
        skills: ['American Pronunciation', 'Campus Vocabulary', 'Note-taking Cơ Bản'],
        expReward: 60,
        coinReward: 40,
        lessons: [
          {
            title: 'Luyện Nói Voice AI: Chuẩn Giọng Anh - Mỹ US Accent',
            type: 'speaking',
            href: '/practice/speaking',
            icon: '🎙️',
            description: 'AI chấm phát âm chi tiết âm nối và trọng âm câu.',
          },
          {
            title: 'Luyện Nghe Tốc Độ: Nghe Đàm Thoại Sinh Viên Campus',
            type: 'listening',
            href: '/practice/listening',
            icon: '🎧',
            description: 'Nghe đoạn thoại trao đổi bài tập & thư viện.',
          },
        ],
      },
      {
        id: 'toefl-node-2',
        stageTitle: 'Mốc 2: Nâng Cấp TOEFL iBT Academic (Target 80+)',
        targetScore: 'TOEFL 80+',
        description: 'Tăng tốc ghi chú bài giảng (Lecture Note-taking) và Integrated Speaking & Writing.',
        skills: ['Lecture Note-taking', 'Integrated Speaking', 'Integrated Writing'],
        expReward: 90,
        coinReward: 60,
        lessons: [
          {
            title: 'Luyện Viết Phản Xạ: Viết Tóm Tắt Bài Giảng Integrated',
            type: 'writing',
            href: '/practice/writing',
            icon: '🖊️',
            description: 'Lắp ghép ý chính và từ nối học thuật.',
          },
          {
            title: 'Ngữ Pháp Lego: Cấu Trúc Câu Tóm Tắt & So Sánh',
            type: 'grammar',
            href: '/grammar',
            icon: '🧱',
            description: 'Biến đổi câu nhanh chóng với công tắc thì.',
          },
        ],
      },
      {
        id: 'toefl-node-3',
        stageTitle: 'Mốc 3: Chinh Phục TOEFL iBT Master (Target 100+)',
        targetScore: 'TOEFL 100+',
        description: 'Thành thạo bài giảng khoa học phức tạp (Biology, History, Astronomy) và bài luận Academic.',
        skills: ['Advanced Academic Lecture', 'Independent Essay', 'Critical Thinking'],
        expReward: 120,
        coinReward: 80,
        lessons: [
          {
            title: 'Bách Khoa Từ Điển: Tra Từ Vựng Khoa Học TOEFL',
            type: 'vocabulary',
            href: '/encyclopedia',
            icon: '📚',
            description: 'Học các thuật ngữ chuyên ngành học thuật.',
          },
          {
            title: 'Lật Flashcards 3D: Ôn Tập Deck TOEFL Academic',
            type: 'flashcards',
            href: '/flashcards',
            icon: '🃏',
            description: 'Ghi nhớ thuật ngữ bằng thuật toán lặp lại ngắt quãng.',
          },
        ],
      },
      {
        id: 'toefl-node-4',
        stageTitle: 'Mốc Cuối: THI THỬ TOEFL iBT MOCK TEST',
        targetScore: 'MOCK TEST TOEFL',
        description: 'Bài thi thử TOEFL iBT chuẩn hóa trên máy tính. Bấm giờ và nhận kết quả tức thì.',
        skills: ['Thi Bấm Giờ Máy Tính', 'Đánh Giá Điểm TOEFL', 'Nhận Báo Cáo Phân Tích'],
        expReward: 160,
        coinReward: 100,
        isMockTest: true,
        lessons: [
          {
            title: 'Vào Phòng Thi Thử TOEFL iBT Trực Tuyến',
            type: 'exam',
            href: '/exam?category=toefl',
            icon: '🏆',
            description: 'Thực hiện bài kiểm tra TOEFL iBT.',
          },
        ],
      },
    ],
  },

  it_work: {
    id: 'it_work',
    examCode: 'it_work',
    title: 'Lộ Trình Tiếng Anh IT & Công Sở Thực Chiến',
    badge: 'Chuyên Ngành IT & Communication',
    icon: '💻',
    color: 'from-teal-500 to-emerald-600',
    badgeBg: 'bg-teal-100',
    badgeText: 'text-teal-900 border-teal-300',
    description: 'Dành riêng cho Lập trình viên, Tester, PM & Nhân sự Công nghệ phản xạ tiếng Anh tự tin trong công việc.',
    targetScores: ['Standup Starter', 'Code Review Pro', 'Tech Lead Pitching', 'Thi Thử Phỏng Vấn IT'],
    nodes: [
      {
        id: 'it-node-1',
        stageTitle: 'Mốc 1: Daily Standup & Báo Cáo Tiến Độ IT (Starter)',
        targetScore: 'Daily Standup',
        description: 'Tự tin trình bày 3 câu hỏi Daily Standup: Hôm qua làm gì, hôm nay làm gì và có Blocker gì không.',
        skills: ['Daily Standup', 'Báo Cáo Blocker', 'Từ Vựng Jira & Agile', 'Dự Báo Tiến Độ'],
        expReward: 50,
        coinReward: 30,
        lessons: [
          {
            title: 'Đóng Vai Kịch Bản: Daily Scrum với Tech Lead Alex',
            type: 'roleplay',
            href: '/practice/roleplay',
            icon: '🎮',
            description: 'Mô phỏng buổi họp Standup 15 phút đầu ngày chuẩn Agile Scrum.',
          },
          {
            title: 'Luyện Nói Voice AI: Trình Bày Blocker & Dự Báo Tiến Độ',
            type: 'speaking',
            href: '/practice/speaking',
            icon: '🎙️',
            description: 'AI kiểm tra phát âm chuẩn IPA các thuật ngữ IT và cấu trúc báo cáo tiến độ.',
          },
          {
            title: 'Luyện Nghe Tốc Độ: Nghe Họp Standup Đội Ngũ Toàn Cầu 3 Múi Giờ',
            type: 'listening',
            href: '/practice/listening',
            icon: '🎧',
            description: 'Luyện nghe phản xạ khi các kỹ sư London, Hà Nội và Mỹ đồng bộ ticket.',
          },
          {
            title: 'Luyện Viết Phản Xạ: Viết Tin Nhắn Standup Trên Kênh Slack',
            type: 'writing',
            href: '/practice/writing',
            icon: '🖊️',
            description: 'Ghép khối từ báo cáo tiến độ và đẩy nhánh staging cho đội kiểm thử.',
          },
          {
            title: 'Học Ngữ Pháp Lego: Công Tắc Chuyển Thì Báo Cáo Jira',
            type: 'grammar',
            href: '/grammar',
            icon: '🧱',
            description: 'Lắp ghép chủ ngữ, hành động và thời gian khi cập nhật ticket.',
          },
        ],
      },
      {
        id: 'it-node-2',
        stageTitle: 'Mốc 2: Code Review, Bug Report & Xử Lý Sự Cố Production (Pro)',
        targetScore: 'Code Review & PR',
        description: 'Viết comment Pull Request chuyên nghiệp, mô tả các bước tái hiện lỗi và ứng cứu sự cố hệ thống sập trong War Room.',
        skills: ['Comment Pull Request', 'Mô Tả Bug Report', 'War Room Sự Cố P1', 'Phân Tích Nguyên Nhân Gốc (RCA)'],
        expReward: 80,
        coinReward: 50,
        lessons: [
          {
            title: 'Đóng Vai War Room: Xử Lý Sự Cố Hệ Thống Sập Production',
            type: 'roleplay',
            href: '/practice/roleplay',
            icon: '🚨',
            description: 'Cùng Incident Commander điều tra lượng lỗi 500 tăng vọt và rollback khẩn cấp.',
          },
          {
            title: 'Luyện Nói Voice AI: Tái Hiện Bug & Phân Tích Memory Leak',
            type: 'speaking',
            href: '/practice/speaking',
            icon: '🎙️',
            description: 'Phát âm chuẩn các thuật ngữ reproducing edge case, CPU spike và hotfix.',
          },
          {
            title: 'Luyện Viết Phản Xạ: Viết Bug Report Ticket & Báo Cáo RCA',
            type: 'writing',
            href: '/practice/writing',
            icon: '🖊️',
            description: 'Thực hành viết tóm tắt lỗi 2MB avatar và giải trình nguyên nhân gốc rễ Post-Mortem.',
          },
          {
            title: 'Luyện Nghe Tốc Độ: Nghe Điều Tra 504 Gateway Timeouts',
            type: 'listening',
            href: '/practice/listening',
            icon: '🎧',
            description: 'Luyện kỹ năng bắt từ khóa khi đội SRE phân tích tắc nghẽn connection pool.',
          },
          {
            title: 'Kho Từ Vựng IT: 100 Thuật Ngữ Lập Trình Thường Dùng',
            type: 'vocabulary',
            href: '/vocabulary',
            icon: '✨',
            description: 'Thuật ngữ Refactor, Deployment, Pipeline, Workaround, Hotfix.',
          },
        ],
      },
      {
        id: 'it-node-3',
        stageTitle: 'Mốc 3: Phỏng Vấn IT Chuẩn STAR, Architecture Pitching & Networking (Master)',
        targetScore: 'Tech Pitching & Interview',
        description: 'Chinh phục phỏng vấn kỹ thuật theo phương pháp STAR, hỏi ngược nhà tuyển dụng và kết nối networking tại hội thảo quốc tế.',
        skills: ['Phương Pháp STAR Phỏng Vấn', 'Elevator Pitch Kỹ Thuật', 'Networking Hội Thảo', 'Thương Lượng Deadline'],
        expReward: 110,
        coinReward: 70,
        lessons: [
          {
            title: 'Đóng Vai Phỏng Vấn STAR: Kỹ Năng Hành Vi & Giải Quyết Xung Đột',
            type: 'roleplay',
            href: '/practice/roleplay',
            icon: '👩‍💼',
            description: 'Mô phỏng vòng phỏng vấn chuyên sâu với VP of Engineering.',
          },
          {
            title: 'Luyện Nói Voice AI: Elevator Pitch 4 Năm Kinh Nghiệm & Hỏi Ngược Tech Lead',
            type: 'speaking',
            href: '/practice/speaking',
            icon: '🎙️',
            description: 'Rèn luyện ngữ điệu tự tin, đĩnh đạc và tầm nhìn công nghệ.',
          },
          {
            title: 'Đóng Vai Networking: Giao Lưu Kết Bạn Tại Sự Kiện Quốc Tế',
            type: 'roleplay',
            href: '/practice/roleplay',
            icon: '✨',
            description: 'Phá băng, thảo luận về serverless resilience và kết nối LinkedIn với Cloud Architect Emma.',
          },
          {
            title: 'Luyện Viết Phản Xạ: Email Cảm Ơn Sau Phỏng Vấn (Thank-You Note)',
            type: 'writing',
            href: '/practice/writing',
            icon: '🖊️',
            description: 'Viết email cảm ơn tinh tế, chuyên nghiệp gửi nhà tuyển dụng sau phỏng vấn.',
          },
          {
            title: 'Bách Khoa Cambridge: Tra Từ Điển IT & Kiến Trúc Hệ Thống',
            type: 'vocabulary',
            href: '/encyclopedia',
            icon: '📚',
            description: 'Tra cứu thuật ngữ microservices, scalability và eventual consistency.',
          },
        ],
      },
      {
        id: 'it-node-4',
        stageTitle: 'Mốc Cuối: THI THỬ PHỎNG VẤN IT MOCK TEST',
        targetScore: 'IT INTERVIEW TEST',
        description: 'Bài test mô phỏng phỏng vấn IT Tiếng Anh thực tế. Đánh giá khả năng phản xạ và vốn từ chuyên ngành.',
        skills: ['Thi Bấm Giờ IT Test', 'Đánh Giá Phản Xạ', 'Nhận Huy Hiệu IT English Master'],
        expReward: 150,
        coinReward: 100,
        isMockTest: true,
        lessons: [
          {
            title: 'Bắt Đầu Bài Thi Thử IT English Trực Tuyến',
            type: 'exam',
            href: '/exam?category=it-tech',
            icon: '🏆',
            description: 'Vào làm bài thi khảo thí bấm giờ.',
          },
        ],
      },
    ],
  },

  daily_comm: {
    id: 'daily_comm',
    examCode: 'daily_comm',
    title: 'Lộ Trình Tiếng Anh Giao Tiếp & Du Lịch Thực Chiến',
    badge: 'Phản Xạ Tự Nhiên & Du Lịch 360°',
    icon: '🌍',
    color: 'from-amber-500 via-rose-500 to-pink-500',
    badgeBg: 'bg-rose-100',
    badgeText: 'text-rose-900 border-rose-300',
    description: 'Chinh phục phản xạ đàm thoại đời sống: Gọi món nhà hàng & Cà phê, Hỏi đường di chuyển, Mua sắm trả giá, và Giao lưu kết bạn tự tin.',
    targetScores: ['Small Talk Căn Bản', 'Khám Phá & Du Lịch', 'Mua Sắm & Đàm Phán', 'Làm Chủ Phản Xạ'],
    nodes: [
      {
        id: 'daily-node-1',
        stageTitle: 'Mốc 1: Gọi Món Nhà Hàng, Quán Cà Phê & Small Talk Căn Bản',
        targetScore: 'Cafe & Restaurant',
        description: 'Tự tin bước vào quán cà phê specialty hay nhà hàng quốc tế: gọi món theo gu, tùy chỉnh đồ uống, hỏi món đặc sản và chia hóa đơn lịch sự.',
        skills: ['Gọi Món Quán Cà Phê', 'Món Đặc Sản Nhà Hàng', 'Chia Tiền Hóa Đơn', 'Icebreaker Đầu Tuần'],
        expReward: 60,
        coinReward: 40,
        lessons: [
          {
            title: 'Luyện Nói Voice AI: Tùy Chỉnh Đồ Uống & Gọi Món Bếp Trưởng',
            type: 'speaking',
            href: '/practice/speaking',
            icon: '🎙️',
            description: 'Luyện phát âm chuẩn IPA: Americano đá, sữa yến mạch, nửa độ ngọt và món chef special.',
          },
          {
            title: 'Đóng Vai Kịch Bản: Thưởng Thức Cà Phê Specialty với Barista Liam',
            type: 'roleplay',
            href: '/practice/roleplay',
            icon: '☕',
            description: 'Mô phỏng order cà phê hạt Ethiopia, bánh cinnamon roll và thanh toán thẻ không chạm.',
          },
          {
            title: 'Luyện Nghe Tốc Độ: Nghe Tư Vấn Hạt Đơn Nguồn Gốc & Sữa Hạt',
            type: 'listening',
            href: '/practice/listening',
            icon: '🎧',
            description: 'Nghe barista bản xứ giới thiệu hương vị hoa quả và các lựa chọn sữa thực vật.',
          },
          {
            title: 'Luyện Viết Phản Xạ: Đặt Bàn Ăn Tối & Hỏi Dị Ứng Thực Phẩm',
            type: 'writing',
            href: '/practice/writing',
            icon: '🖊️',
            description: 'Ghép câu đặt bàn cạnh cửa sổ lúc 7 giờ tối và kiểm tra thành phần dị ứng sữa/hạt.',
          },
          {
            title: 'Lật Flashcards 3D: 100 Từ Vựng Ăn Uống & Hương Vị Ẩm Thực',
            type: 'flashcards',
            href: '/flashcards',
            icon: '🃏',
            description: 'Ôn tập từ vựng ẩm thực, tráng miệng, mức độ chín của bít tết theo thuật toán SRS.',
          },
        ],
      },
      {
        id: 'daily-node-2',
        stageTitle: 'Mốc 2: Hỏi Đường, Đi Tàu Điện Ngầm & Di Chuyển Du Lịch',
        targetScore: 'Travel & Navigation',
        description: 'Làm chủ kỹ năng di chuyển khi đi du lịch: hỏi tuyến tàu điện ngầm, mua vé ngày không giới hạn, tìm lối ra và xác định khoảng cách đi bộ.',
        skills: ['Tuyến Metro & Sân Ga', 'Tàu Express vs Local', 'Chỉ Đường Đi Bộ', 'Thủ Tục Đổi Chuyến'],
        expReward: 90,
        coinReward: 60,
        lessons: [
          {
            title: 'Luyện Nói Voice AI: Hỏi Tuyến Tàu Điện Ngầm & Đi Bộ Đến Bảo Tàng',
            type: 'speaking',
            href: '/practice/speaking',
            icon: '🎙️',
            description: 'Rèn luyện các mẫu câu hỏi đường lịch sự: within walking distance, transfer station.',
          },
          {
            title: 'Đóng Vai Kịch Bản: Mua Thẻ Vé Ngày & Tìm Sân Ga cùng Station Master Ken',
            type: 'roleplay',
            href: '/practice/roleplay',
            icon: '🚇',
            description: 'Mô phỏng mua Day Pass tại máy tự động và hỏi đường đến Bảo tàng Metropolitan.',
          },
          {
            title: 'Luyện Nghe Tốc Độ: Nghe Thông Báo Đổi Sân Ga & Tàu Tốc Hành',
            type: 'listening',
            href: '/practice/listening',
            icon: '🎧',
            description: 'Phân biệt thông báo tàu Express bỏ trạm và đổi sang tàu Local ở sân ga số 2.',
          },
          {
            title: 'Luyện Viết Phản Xạ: Hướng Dẫn Chỉ Đường Chi Tiết Đến Điểm Tham Quan',
            type: 'writing',
            href: '/practice/writing',
            icon: '🖊️',
            description: 'Lắp ghép câu chỉ dẫn: đi thẳng 2 dãy nhà và rẽ trái tại ngã tư có đèn tín hiệu.',
          },
          {
            title: 'Học Ngữ Pháp Lego: Giới Từ Vị Trí & Cấu Trúc Chỉ Hướng Trực Quan',
            type: 'grammar',
            href: '/grammar',
            icon: '🧱',
            description: 'Trực quan hóa khối câu chỉ phương hướng và vị trí không gian.',
          },
        ],
      },
      {
        id: 'daily-node-3',
        stageTitle: 'Mốc 3: Mua Sắm, Trả Giá Văn Minh & Hoàn Thuế Du Lịch',
        targetScore: 'Shopping & Bargaining',
        description: 'Nghệ thuật mua sắm thông minh: hỏi kích cỡ trong phòng thử đồ, đàm phán giảm giá combo lịch thiệp và làm thủ tục hoàn thuế VAT.',
        skills: ['Hỏi Size & Phòng Thử Đồ', 'Trả Giá Văn Minh (Bundle Deal)', 'Thủ Tục Hoàn Thuế VAT', 'Đổi Trả Sản Phẩm'],
        expReward: 120,
        coinReward: 80,
        lessons: [
          {
            title: 'Luyện Nói Voice AI: Hỏi Size Áo Khoác & Đàm Phán Giảm Giá Combo',
            type: 'speaking',
            href: '/practice/speaking',
            icon: '🎙️',
            description: 'Phát âm chuẩn các mẫu câu mua sắm tinh tế: fitting room, bundle discount, ceramic vases.',
          },
          {
            title: 'Đóng Vai Kịch Bản: Mua Sắm Đồ Thủ Công & Xin Giấy Hoàn Thuế với Clara',
            type: 'roleplay',
            href: '/practice/roleplay',
            icon: '🛍️',
            description: 'Mô phỏng thương lượng chiết khấu combo 3 món và nhận hóa đơn hoàn thuế tại quầy.',
          },
          {
            title: 'Luyện Nghe Tốc Độ: Nghe Hướng Dẫn Hoàn Thuế VAT Tại Tầng 6',
            type: 'listening',
            href: '/practice/listening',
            icon: '🎧',
            description: 'Nghe điều kiện hoàn thuế: mang hộ chiếu gốc và hóa đơn trên 100 đô la.',
          },
          {
            title: 'Luyện Viết Phản Xạ: Đổi Cỡ Áo Trong 7 Ngày & Yêu Cầu Phòng Khách Sạn',
            type: 'writing',
            href: '/practice/writing',
            icon: '🖊️',
            description: 'Viết câu hỏi đổi size áo khi còn biên lai và ghi chú phòng khách sạn có ban công nhìn biển.',
          },
          {
            title: 'Sổ Từ Bookmark: Ôn Tập Các Thuật Ngữ Mua Sắm Đã Lưu',
            type: 'vocabulary',
            href: '/bookmarks',
            icon: '🔖',
            description: 'Củng cố các từ vựng bôi đen tra cứu khi đọc tin tức thời trang và mua sắm quốc tế.',
          },
        ],
      },
      {
        id: 'daily-node-4',
        stageTitle: 'Mốc Cuối: TỔNG HỢP PHẢN XẠ & GIAO LƯU NETWORKING QUỐC TẾ',
        targetScore: 'MOCK TEST GIAO TIẾP',
        description: 'Vượt qua bài kiểm tra phản xạ đàm thoại toàn diện và thực hành kỹ năng Networking kết bạn tự nhiên với bạn bè thế giới.',
        skills: ['Networking & Small Talk', 'Giữ Liên Lạc LinkedIn', 'Phản Xạ Tức Thì', 'Nhận Chứng Chỉ Giao Tiếp Master'],
        expReward: 160,
        coinReward: 100,
        isMockTest: true,
        lessons: [
          {
            title: 'Luyện Nói Voice AI: Small Talk Cuối Tuần & Kết Nối Mạng Xã Hội',
            type: 'speaking',
            href: '/practice/speaking',
            icon: '🎙️',
            description: 'Nói trôi chảy câu bắt chuyện mở đầu tuần mới và lời mời trao đổi LinkedIn.',
          },
          {
            title: 'Đóng Vai Kịch Bản: Giao Lưu Kết Bạn & Networking Hội Thảo với Emma',
            type: 'roleplay',
            href: '/practice/roleplay',
            icon: '✨',
            description: 'Mô phỏng trò chuyện giờ giải lao, thảo luận chủ đề công nghệ và quét mã QR LinkedIn.',
          },
          {
            title: 'Luyện Nghe Tốc Độ: Đàm Thoại Kết Nối Sau Bài Keynote Kiến Trúc',
            type: 'listening',
            href: '/practice/listening',
            icon: '🎧',
            description: 'Nghe lời rủ đi dự buổi giao lưu tiệc tối trên sân thượng khách sạn.',
          },
          {
            title: 'Vào Trung Tâm Khảo Thí: Bài Thi Thử Giao Tiếp Đời Sống Bấm Giờ',
            type: 'exam',
            href: '/exam?category=daily',
            icon: '🏆',
            description: 'Làm bài thi trắc nghiệm bấm giờ đánh giá phản xạ giao tiếp đời sống thực tế.',
          },
        ],
      },
    ],
  },
};
