export const CINNAMOROLL_ALLOWED_EMAILS = [
  'xuanmai032004@gmail.com',
  'liuyufishball@gmail.com',
  '22520841@gm.uit.edu.vn',
];

export function checkCinnamorollAccess(user: { email?: string | null; email_verified?: boolean | number } | null | undefined): {
  isUnlocked: boolean;
  status: 'locked_not_logged_in' | 'locked_unauthorized_email' | 'locked_unverified_email' | 'unlocked';
  message: string;
} {
  if (!user) {
    return {
      isUnlocked: false,
      status: 'locked_not_logged_in',
      message: 'Bé Cinnamoroll là Thú Cưng Độc Quyền Giới Hạn dành riêng cho Quản Trị Viên (Admin). Vui lòng đăng nhập để kiểm tra điều kiện mở khoá!',
    };
  }

  const userEmail = (user.email || '').trim().toLowerCase();
  if (!userEmail) {
    return {
      isUnlocked: false,
      status: 'locked_unauthorized_email',
      message: '🔒 Bé Cinnamoroll là Thú Cưng Độc Quyền Giới Hạn chỉ dành riêng cho Quản Trị Viên (Admin) được cấp quyền.',
    };
  }

  const isEmailAllowed = CINNAMOROLL_ALLOWED_EMAILS.some((e) => e.toLowerCase() === userEmail);
  if (!isEmailAllowed) {
    return {
      isUnlocked: false,
      status: 'locked_unauthorized_email',
      message: '🔒 Bé Cinnamoroll là Thú Cưng Độc Quyền Giới Hạn chỉ dành riêng cho Quản Trị Viên (Admin) được cấp quyền đặc biệt.',
    };
  }

  const isVerified = user.email_verified === true || user.email_verified === 1;
  if (!isVerified) {
    return {
      isUnlocked: false,
      status: 'locked_unverified_email',
      message: '✉️ Tài khoản của bạn đủ điều kiện kích hoạt đặc quyền sở hữu bé Cinnamoroll! Vui lòng hoàn tất xác thực mã OTP email để mở khoá bé về khu vườn của mình.',
    };
  }

  return {
    isUnlocked: true,
    status: 'unlocked',
    message: '🎉 Chúc mừng Quản Trị Viên! Bạn đã mở khoá thành công bé Cinnamoroll Bồng Bềnh!',
  };
}

export interface PetConfig {
  id: string;
  name: string;
  species: string;
  emoji: string;
  avatarBg: string;
  description: string;
  isSpecialVip?: boolean;
  requiredEmails?: string[];
  buff: {
    title: string;
    description: string;
    bonusType: 'exp' | 'listening' | 'streak' | 'writing' | 'speaking' | 'speed' | 'coins' | 'all';
    bonusPercent: number;
  };
  greetings: string[];
  eatSounds: string[];
  happyQuotes: string[];
}

export interface ShopItem {
  id: string;
  name: string;
  type: 'hat' | 'outfit' | 'accessory' | 'habitat' | 'food' | 'decor';
  categoryLabel: string;
  price: number;
  emoji: string;
  description: string;
  benefit?: string;
  hungerBoost?: number;
  happinessBoost?: number;
  energyBoost?: number;
  expBoost?: number;
}

export const PETS_CATALOG: Record<string, PetConfig> = {
  owl: {
    id: 'owl',
    name: 'Lexi Trí Tuệ',
    species: 'Cú Thông Thái',
    emoji: '🦉',
    avatarBg: 'from-emerald-400 to-teal-500',
    description: 'Bậc thầy cú mèo uyên bác, thích đọc sách ngữ pháp và khám phá từ điển 26.500+ từ vựng.',
    buff: {
      title: 'Học Giả Uyên Bác',
      description: '+15% EXP thưởng cho mọi bài học Từ Vựng & Ngữ Pháp Lego',
      bonusType: 'exp',
      bonusPercent: 15,
    },
    greetings: [
      'Chào bạn! Hôm nay chúng mình cùng học thêm 10 từ mới nhé!',
      'Hoot hoot! Bạn phát âm từ vựng hôm nay chuẩn lắm!',
      'Trí tuệ tích lũy từng ngày, kiên trì là số một!',
    ],
    eatSounds: ['Hooom! Ngon tuyệt!', 'Năng lượng đọc sách đã đầy!', 'Hoot! Cảm ơn bạn nha!'],
    happyQuotes: [
      'Bạn là người bạn học tuyệt nhất của mình!',
      'Mỗi ngày học là một ngày tỏa sáng!',
      'Cùng nhau chinh phục tiếng Anh bản xứ nào!',
    ],
  },
  cat: {
    id: 'cat',
    name: 'Mochi Nhanh Nhẹn',
    species: 'Mèo Shiba Con',
    emoji: '🐱',
    avatarBg: 'from-amber-400 to-orange-400',
    description: 'Chú mèo lanh lợi, tai siêu thính giúp bạn nghe bắt trọn từng âm tiết khó nhất.',
    buff: {
      title: 'Tai Mèo Thính Nhạy',
      description: '+15% Điểm số và Coins khi Luyện Nghe Tốc Độ & Flashcard',
      bonusType: 'listening',
      bonusPercent: 15,
    },
    greetings: [
      'Meow! Bạn đã sẵn sàng luyện nghe cùng mình chưa?',
      'Purr... Chúc bạn một ngày học tập ngập tràn niềm vui!',
      'Meow! Lật thêm vài thẻ Flashcard nhé!',
    ],
    eatSounds: ['Măm măm meow!', 'Ngon quá đi à!', 'Purr purr... no nê rồi!'],
    happyQuotes: [
      'Meowww! Được vuốt ve thích quá đi!',
      'Bạn học giỏi quá chừng, mình tự hào về bạn!',
      'Cố lên nào, mục tiêu hôm nay sắp hoàn thành rồi!',
    ],
  },
  dog: {
    id: 'dog',
    name: 'Taro Trung Thành',
    species: 'Chó Shiba Dũng Cảm',
    emoji: '🐶',
    avatarBg: 'from-orange-400 to-amber-500',
    description: 'Chú cún Shiba siêu kiên cường, luôn nhắc nhở bạn giữ vững ngọn lửa Streak mỗi ngày.',
    buff: {
      title: 'Chiến Binh Bền Bỉ',
      description: 'Gấp đôi Coins thưởng mỗi khi duy trì chuỗi ngày Streak liên tục',
      bonusType: 'streak',
      bonusPercent: 100,
    },
    greetings: [
      'Gâu gâu! Lửa Streak hôm nay cháy rực rỡ quá bạn ơi!',
      'Đừng bỏ cuộc nhé! Taro luôn ở đây đồng hành cùng bạn!',
      'Gâu! Hãy nói tiếng Anh thật to và dõng dạc nào!',
    ],
    eatSounds: ['Ngon bá cháy gâu gâu!', 'Nạp đầy pin rồi, học tiếp thôi!', 'Gâu! Tuyệt vời ông mặt trời!'],
    happyQuotes: [
      'Gâu gâu! Được bạn cưng nựng là vui nhất!',
      'Chúng ta là cặp bài trùng học tiếng Anh số 1!',
      'Cứ kiên trì là bạn sẽ nói tiếng Anh lưu loát thôi!',
    ],
  },
  fox: {
    id: 'fox',
    name: 'Kitsune Tinh Anh',
    species: 'Cáo Thông Minh',
    emoji: '🦊',
    avatarBg: 'from-red-400 to-orange-500',
    description: 'Chú cáo sắc sảo, bậc thầy phản xạ trong các tình huống giao tiếp công sở phức tạp.',
    buff: {
      title: 'Mẹo Hay Chiến Thuật',
      description: 'Mở khóa gợi ý miễn phí và +15% điểm khi Luyện Viết & Đóng Vai Scrum',
      bonusType: 'writing',
      bonusPercent: 15,
    },
    greetings: [
      'Hôm nay chúng ta sẽ phản xạ hội thoại với Tech Lead Alex nhé!',
      'Từ ngữ là sức mạnh, dùng đúng từ sẽ thuyết phục tất cả!',
      'Kitsune đã chuẩn bị xong các câu hỏi hóc búa rồi đây!',
    ],
    eatSounds: ['Ngon tinh tế!', 'Hương vị tuyệt hảo!', 'Năng lượng trí tuệ đã phục hồi!'],
    happyQuotes: [
      'Bạn tư duy logic rất tốt!',
      'Cách bạn ghép câu tiếng Anh ngày càng tự nhiên đấy!',
      'Tuyệt vời! Tiếp tục phát huy nhé!',
    ],
  },
  panda: {
    id: 'panda',
    name: 'Bambu Tĩnh Tâm',
    species: 'Gấu Trúc Ấm Áp',
    emoji: '🐼',
    avatarBg: 'from-teal-400 to-emerald-500',
    description: 'Bậc thầy kiên nhẫn, giúp bạn thở đều và phát âm từng nguyên âm IPA thật tự tin.',
    buff: {
      title: 'Thanh Âm Chuẩn Mực',
      description: '+15% Điểm âm điệu và chính xác khi Luyện Nói AI Voice',
      bonusType: 'speaking',
      bonusPercent: 15,
    },
    greetings: [
      'Hít một hơi thật sâu... và cùng mình phát âm từ này nhé!',
      'Không việc gì phải vội, cứ tự tin nói từng chữ một!',
      'Bambu thích giọng nói ấm áp của bạn lắm!',
    ],
    eatSounds: ['Nhai rôm rốp ngon quá!', 'Bụng no tròn rồi nè!', 'Ngon miệng cực kỳ!'],
    happyQuotes: [
      'Cảm giác bình yên bên bạn thật tuyệt!',
      'Bạn phát âm tiến bộ rõ rệt từng ngày đấy!',
      'Hãy tin vào chính mình, bạn làm được mà!',
    ],
  },
  bunny: {
    id: 'bunny',
    name: 'Lola Năng Động',
    species: 'Thỏ Tốc Độ',
    emoji: '🐰',
    avatarBg: 'from-pink-400 to-rose-400',
    description: 'Cô thỏ hoạt bát, luôn tràn đầy năng lượng nhảy nhót và tăng tốc độ phản xạ giao tiếp.',
    buff: {
      title: 'Tia Chớp Phản Xạ',
      description: '+20% Coins và tốc độ phản hồi khi hoàn thành bài tập nhanh',
      bonusType: 'speed',
      bonusPercent: 20,
    },
    greetings: [
      'Boing boing! Nhảy vào học ngay thôi nào!',
      'Chào buổi sáng tràn đầy năng lượng tích cực nha!',
      'Bạn hôm nay trông thật năng lượng và sẵn sàng!',
    ],
    eatSounds: ['Cà rốt giòn ngọt quá!', 'Boing! Đầy năng lượng rồi!', 'Cảm ơn bạn nhiều nha!'],
    happyQuotes: [
      'Yeeey! Nhảy cùng Lola nào!',
      'Bạn là học viên năng nổ và đáng yêu nhất!',
      'Tốc độ phản xạ của bạn đã đạt mốc thần tốc rồi!',
    ],
  },
  hello_kitty: {
    id: 'hello_kitty',
    name: 'Hello Kitty Đáng Yêu',
    species: 'Mèo Sanrio Trứ Danh',
    emoji: '🎀',
    avatarBg: 'from-rose-400 to-pink-500',
    description: 'Biểu tượng toàn cầu với nơ đỏ trứ danh, luôn lan tỏa tình yêu thương và sự chăm chỉ học tập.',
    buff: {
      title: 'Trái Tim Nhân Ái',
      description: '+20% EXP & Coins cho mọi bài học và thử thách giao tiếp',
      bonusType: 'exp',
      bonusPercent: 20,
    },
    greetings: [
      'Chào bạn! Mình là Hello Kitty, hôm nay chúng mình cùng học thật vui nhé! 🎀',
      'Bạn phát âm chuẩn và đáng yêu lắm!',
      'Một ngày mới ngập tràn niềm vui và từ vựng mới cùng Kitty nhé!',
    ],
    eatSounds: ['Măm măm ngon quá! 🍎', 'Bánh táo nướng ngọt lịm!', 'Cảm ơn bạn yêu dấu! 🎀'],
    happyQuotes: [
      'Được làm bạn với bạn là điều tuyệt vời nhất! 💖',
      'Cùng Kitty cố gắng mỗi ngày nha!',
      'Bạn học giỏi xuất sắc luôn! ✨',
    ],
  },
  kuromi: {
    id: 'kuromi',
    name: 'Kuromi Cá Tính',
    species: 'Thỏ Sanrio Tinh Nghịch',
    emoji: '😈',
    avatarBg: 'from-purple-600 to-slate-900',
    description: 'Cô nàng thỏ tinh nghịch với mũ hề đen và đầu lâu hồng, truyền lửa tự tin và năng lượng bứt phá.',
    buff: {
      title: 'Bứt Phá Cá Tính',
      description: '+25% Điểm Streak & Tốc độ làm bài giao tiếp thực chiến',
      bonusType: 'streak',
      bonusPercent: 125,
    },
    greetings: [
      'Heheh! Kuromi đây! Sẵn sàng quậy banh nóc cùng tiếng Anh chưa? 🖤',
      'Học là phải chất và thật phong cách nha bạn tôi!',
      'Đừng để ngọn lửa Streak bị dập tắt đấy, Kuromi đang canh chừng đó! 🔥',
    ],
    eatSounds: ['Nho tím ngọt lịm ngon xỉu! 🍇', 'Nạp đầy năng lượng quậy tiếp thôi!', 'Quá đã luôn bạn ơi! 💜'],
    happyQuotes: [
      'Heheh, bạn vuốt ve làm Kuromi ngại ghê á! 😈',
      'Chúng ta là đội quân ngầu nhất quả đất!',
      'Cứ thế mà tiến lên, không sợ ai hết! 🚀',
    ],
  },
  cinnamoroll: {
    id: 'cinnamoroll',
    name: 'Cinnamoroll Bồng Bềnh',
    species: 'Cún Mây Sanrio',
    emoji: '☁️',
    avatarBg: 'from-sky-300 to-blue-400',
    isSpecialVip: true,
    requiredEmails: CINNAMOROLL_ALLOWED_EMAILS,
    description: 'Chú cún trắng sinh ra từ đám mây bồng bềnh, đôi tai dài có thể bay lượn và lắng nghe vạn vật. (Đặc Quyền Dành Riêng Admin)',
    buff: {
      title: 'Đôi Cánh Diệu Kỳ',
      description: '+20% Điểm số và Coins khi Luyện Nghe Tốc Độ & Flashcard',
      bonusType: 'listening',
      bonusPercent: 20,
    },
    greetings: [
      'Gâu gâu! Mình vừa bay từ quán cafe mây xuống đây học cùng bạn nè! ☁️',
      'Tai mình to và thính lắm, cùng nhau bắt trọn từng âm điệu nhé! 🎧',
      'Chúc bạn một ngày học nhẹ nhàng như làn mây trắng!',
    ],
    eatSounds: ['Bánh cuộn quế thơm lừng giòn tan! 🥐', 'Ngon ngọt như mây bồng bềnh!', 'Cảm ơn bạn tốt bụng! ☁️'],
    happyQuotes: [
      'Được bay lượn bên bạn thích quá đi! ✨',
      'Bạn nghe chuẩn từng từ luôn á, tuyệt ghê!',
      'Cùng bay cao với ước mơ tiếng Anh nào! 🌟',
    ],
  },
  my_melody: {
    id: 'my_melody',
    name: 'My Melody Dịu Dàng',
    species: 'Thỏ Khăn Hồng Sanrio',
    emoji: '🌸',
    avatarBg: 'from-pink-300 to-rose-400',
    description: 'Cô thỏ hiền dịu đội mũ trùm đầu màu hồng, luôn kiên nhẫn đồng hành và vỗ về trong từng bài học khó.',
    buff: {
      title: 'Giai Điệu Thuần Khiết',
      description: '+20% Điểm Âm Điệu khi Luyện Nói AI Voice & Phát Âm IPA',
      bonusType: 'speaking',
      bonusPercent: 20,
    },
    greetings: [
      'Xin chào bạn! Melody chúc bạn một ngày học thật ngọt ngào như kẹo bông! 🌸',
      'Cứ tự tin phát âm từng chữ một nhé, Melody luôn ở đây lắng nghe bạn!',
      'Những giai điệu tiếng Anh hôm nay du dương tuyệt vời!',
    ],
    eatSounds: ['Dâu tây tươi ngọt lịm ngon tuyệt! 🍓', 'Melody no bụng rồi nè, cảm ơn bạn!', 'Măm măm ngọt ngào quá! 🌸'],
    happyQuotes: [
      'Melody quý bạn nhất trần đời! 💖',
      'Giọng nói của bạn ấm áp và phát âm chuẩn lắm!',
      'Mỗi bước tiến nhỏ đều rất đáng tự hào! 🌷',
    ],
  },
  pompompurin: {
    id: 'pompompurin',
    name: 'Pompompurin Béo Tròn',
    species: 'Cún Golden Sanrio',
    emoji: '🍮',
    avatarBg: 'from-amber-300 to-yellow-500',
    description: 'Chú cún Golden mũ nồi beret mê ngủ và cuồng bánh pudding caramen, mang đến sự thư thái tuyệt đối.',
    buff: {
      title: 'Bữa Tiệc No Nê',
      description: 'Giảm 50% tốc độ đói & Thưởng +15% Coins sau mỗi bài học',
      bonusType: 'exp',
      bonusPercent: 15,
    },
    greetings: [
      'Yummm! Pompompurin vừa chén xong đĩa pudding khổng lồ đây! 🍮',
      'Học vui vẻ không áp lực, vừa học vừa thư giãn bạn nhé!',
      'Bụng no tròn thì học mới vô được chứ nà! Chào bạn!',
    ],
    eatSounds: ['Pudding béo ngậy mềm mịn tan trong miệng! 🍮', 'Ôi ngon mê ly rụng rốn!', 'Bụng bự no tròn xoe rồi! 😋'],
    happyQuotes: [
      'Purin thích nhất là được bạn xoa cái bụng tròn này! 🥰',
      'Cùng nhau tận hưởng niềm vui học tiếng Anh nha!',
      'Bạn giỏi đỉnh của chóp luôn! 🌟',
    ],
  },
  keroppi: {
    id: 'keroppi',
    name: 'Keroppi Bơi Lội',
    species: 'Ếch Xanh Sanrio',
    emoji: '🐸',
    avatarBg: 'from-lime-400 to-emerald-500',
    description: 'Chú ếch xanh mắt to tròn sống bên đầm sen, bậc thầy bơi lội và bật nhảy phản xạ thần tốc.',
    buff: {
      title: 'Bật Nhảy Thần Tốc',
      description: '+25% Điểm Phản Xạ Giao Tiếp Roleplay & Trả Lời Nhanh',
      bonusType: 'speed',
      bonusPercent: 25,
    },
    greetings: [
      'Kero kero! Mình vừa bơi một vòng quanh hồ sen về đây! 🐸🏊',
      'Cùng nhảy vọt qua mọi thử thách bài học hôm nay nào!',
      'Phản xạ nhanh như chớp, nói tiếng Anh tự nhiên như người bản xứ nhé! ⚡',
    ],
    eatSounds: ['Măm măm no nê sảng khoái! 🪷', 'Kero kero! Đầy năng lượng rồi!', 'Cảm ơn bạn nhiều nha! 🐸'],
    happyQuotes: [
      'Keroppi nhảy cẫng lên vì vui sướng nè! 🎉',
      'Bạn bơi lội và học bài đều siêu cừ khôi!',
      'Cứ thế bứt phá đỉnh cao nhé! 🚀',
    ],
  },

  // ==================== ONE PIECE ====================
  chopper: {
    id: 'chopper',
    name: 'Tony Tony Chopper',
    species: 'Tuần Lộc Bác Sĩ Mũ Rơm',
    emoji: '🦌',
    avatarBg: 'from-pink-400 to-blue-500',
    description: 'Bác sĩ tuần lộc đáng yêu của băng Mũ Rơm, thích kẹo bông gòn và luôn tràn đầy năng lượng chữa lành.',
    buff: {
      title: 'Rumble Ball Trí Tuệ',
      description: '+25% EXP & Hồi phục năng lượng siêu tốc sau mỗi bài học',
      bonusType: 'exp',
      bonusPercent: 25,
    },
    greetings: [
      'Kono yaroo! Khen tớ học giỏi tiếng Anh tớ cũng không vui đâu đấy! (nhảy múa) 🌸',
      'Cậu có bị mỏi mệt khi học từ vựng không? Để bác sĩ Chopper khám cho nhé!',
      'Hôm nay chúng mình cùng học bài thật chăm rồi đi ăn kẹo bông gòn nha! 🍭',
    ],
    eatSounds: [
      'Oishii! Kẹo bông gòn ngọt ngào số một trần đời! 🍭',
      'Măm măm! Nạp đầy năng lượng để cùng cậu chinh phục bài học mới!',
      'Ngon xỉu luôn! Chopper thích món này nhất trên đời!',
    ],
    happyQuotes: [
      'Được cậu xoa đầu thích quá đi thôi... đồ ngốc này! 🥰',
      'Chopper sẽ luôn bên cạnh cổ vũ và chăm sóc sức khỏe cho cậu!',
      'Cố lên nào đồng đội! Chúng ta sẽ trở thành Vua Tiếng Anh!',
    ],
  },
  karoo: {
    id: 'karoo',
    name: 'Karoo Vịt Siêu Tốc',
    species: 'Đội Trưởng Vịt Alabasta',
    emoji: '🦆',
    avatarBg: 'from-amber-400 to-yellow-500',
    description: 'Chiến mã trung thành của Công chúa Vivi, chú vịt nhanh nhất đại dương với chiếc mũ phi công ngộ nghĩnh.',
    buff: {
      title: 'Tốc Độ Siêu Tốc Alabasta',
      description: '+25% Tốc độ phản xạ Luyện Nói & Đóng vai giao tiếp',
      bonusType: 'speaking',
      bonusPercent: 25,
    },
    greetings: [
      'Quack quack! (Chào mừng bạn đến với vương quốc Alabasta!) 🦆',
      'Guaaack! Cùng phi nước đại vượt qua 20 câu giao tiếp nào!',
      'Quack! Karoo đã sẵn sàng cõng bạn cán đích bảng xếp hạng!',
    ],
    eatSounds: [
      'Quack quack gobble! Lương khô và nước ngọt sa mạc ngon tuyệt! 💧',
      'Guaaack! No nê rồi, chạy đua thần tốc thôi!',
      'Quack quack! Măm măm sạch bách không còn một hạt!',
    ],
    happyQuotes: [
      'Quackkk! Karoo dụi đầu vào tay bạn thật tình cảm nè! 💕',
      'Guaack! Bạn là người bạn đồng hành cưỡi vịt giỏi nhất thế giới!',
      'Quack quack! Phản xạ nói của bạn hôm nay nhanh như gió lốc!',
    ],
  },
  bepo: {
    id: 'bepo',
    name: 'Bepo Gấu Bắc Cực',
    species: 'Hoa Tiêu Võ Thuật Băng Heart',
    emoji: '🐻❄️',
    avatarBg: 'from-orange-400 to-amber-600',
    description: 'Chú gấu Bắc Cực mặc áo liền quần cam của thuyền trưởng Law, giỏi võ Kungfu nhưng rất hay ngại ngùng xin lỗi.',
    buff: {
      title: 'Hoa Tiêu Thính Giác',
      description: '+20% Điểm nghe audio & Nhận diện ngữ điệu bản xứ',
      bonusType: 'listening',
      bonusPercent: 20,
    },
    greetings: [
      'Tôi xin lỗi vì đã tồn tại... À nhầm, chào bạn, hôm nay cùng luyện nghe nhé! 🐻',
      'Aye Aye Captain! Bepo đã định vị xong tọa độ các bài nghe hóc búa nhất!',
      'Hôm nay trời hơi nóng nhỉ... Nhưng Bepo vẫn quyết tâm học cùng bạn!',
    ],
    eatSounds: [
      'Cá tuyết tươi ngon quá! Cảm ơn bạn nhiều nha! 🐟',
      'Nhai măm măm... Tôi xin lỗi vì lỡ ăn hết phần của bạn...',
      'Ngon tuyệt vời! Bepo nạp đầy năng lượng kungfu rồi!',
    ],
    happyQuotes: [
      'Tôi xin lỗi vì lông tôi mềm quá làm bạn thích vuốt... 🥰',
      'Cậu giỏi tiếng Anh quá, thuyền trưởng Law chắc chắn sẽ khen đấy!',
      'Cảm ơn bạn đã luôn đối xử dịu dàng ấm áp với Bepo!',
    ],
  },

  // ==================== NARUTO ====================
  kurama: {
    id: 'kurama',
    name: 'Cửu Vĩ Kurama Chibi',
    species: 'Cửu Vĩ Hồ Ly Thần Thú',
    emoji: '🦊🔥',
    avatarBg: 'from-orange-600 to-red-600',
    description: 'Hồ ly chín đuôi cam rực lửa phiên bản chibi đáng yêu, mang nguồn chakra vô tận giữ lửa Streak bền bỉ.',
    buff: {
      title: 'Chakra Cửu Vĩ Bền Bỉ',
      description: '+50% Lửa Streak bền bỉ & Chống đứt chuỗi học tập',
      bonusType: 'streak',
      bonusPercent: 50,
    },
    greetings: [
      'Hừ, nhóc con! Đừng hòng lười biếng trước mặt Cửu Vĩ này! 🔥',
      'Khai mở Chakra và học thuộc ngay 10 từ vựng hôm nay đi!',
      'Chakra của ta đang sôi sục, hôm nay phải làm trọn vẹn bài tập đấy!',
    ],
    eatSounds: [
      'Ngon đấy! Tạm thời tha cho ngươi tội dám cho ta ăn ít! 🍖',
      'Măm măm! Chakra hồ ly đã hồi phục 100%!',
      'Thịt nướng đậm vị Konoha! Thêm một đĩa nữa coi!',
    ],
    happyQuotes: [
      'Hừm... Đừng tưởng vuốt chín cái đuôi của ta là ta mềm lòng nhé... mà cũng thích thật! 🦊',
      'Ý chí Hỏa Kế của ngươi rất kiên định, ta công nhận ngươi!',
      'Cứ giữ phong độ này, ngươi sẽ thành Hokage tiếng Anh!',
    ],
  },
  pakkun: {
    id: 'pakkun',
    name: 'Chó Ninja Pakkun',
    species: 'Nhẫn Khuyển Đội Trưởng',
    emoji: '🐶',
    avatarBg: 'from-amber-600 to-stone-700',
    description: 'Chú chó ninja đầu đàn của Kakashi, đeo băng trán Konoha, mũi siêu thính đánh hơi mọi bẫy từ vựng khó.',
    buff: {
      title: 'Đánh Hơi Từ Vựng',
      description: '+20% Điểm từ vựng & Gợi ý ngữ cảnh chính xác',
      bonusType: 'writing',
      bonusPercent: 20,
    },
    greetings: [
      'Này nhóc, mùi từ vựng mới thoang thoảng đâu đây quanh phòng học này! 🐾',
      'Kakashi bảo ta tới giám sát cậu hoàn thành bài tập ngữ pháp hôm nay.',
      'Đệm thịt bàn chân của ta mềm lắm đấy, muốn sờ thử một tí không?',
    ],
    eatSounds: [
      'Xương hầm bổ dưỡng! Tay nghề nấu nướng của cậu duyệt được đấy! 🥩',
      'Ngoàm ngoàm! Đã bụng rồi, lên đường làm nhiệm vụ thôi!',
      'Thức ăn ngon chuẩn cấp S ninja!',
    ],
    happyQuotes: [
      'Gâu! Xoa đệm chân cho ta là chuẩn bài rồi đấy nhóc! 🐾',
      'Khứu giác của ta xác nhận: Trình tiếng Anh của cậu đã lên tầm Jonin!',
      'Làm tốt lắm đồng đội ninja, ta rất tự hào về cậu!',
    ],
  },
  gamakichi: {
    id: 'gamakichi',
    name: 'Cóc Triệu Hồi Gamakichi',
    species: 'Cóc Nhẫn Giả Myoboku',
    emoji: '🐸',
    avatarBg: 'from-amber-500 to-orange-700',
    description: 'Cóc nhẫn giả tinh anh của Núi Myoboku, khoác áo xanh hiphop ninja, thông thạo cấu trúc ngữ pháp logic.',
    buff: {
      title: 'Tiên Thuật Ngữ Pháp',
      description: '+20% Điểm bài tập ngữ pháp & Ghép câu chuẩn xác',
      bonusType: 'speed',
      bonusPercent: 20,
    },
    greetings: [
      'Yo Naruto! À quên, chào người anh em học tiếng Anh nhé! 🐸✌️',
      'Cần thuật triệu hồi hỗ trợ giải mấy câu ngữ pháp hóc búa không?',
      'Bật Tiên Nhân Thuật lên nào, nhìn thấu mọi cấu trúc câu phức tạp!',
    ],
    eatSounds: [
      'Côn trùng tẩm mật ong núi Myoboku giòn rụm thơm ngon! 🪲',
      'Ợ... No căng rốn rồi ông bạn ơi!',
      'Ngon tuyệt cú mèo! Năng lượng Tiên Thuật đầy tràn!',
    ],
    happyQuotes: [
      'Xoa đầu cóc mang lại may mắn cực đỉnh trong bài thi đấy nhé! 🌟',
      'Cậu ghép câu chuẩn không cần chỉnh, đúng chất nhẫn giả!',
      'Hôm nay phong độ đỉnh cao thật, Myoboku xin bái phục!',
    ],
  },

  // ==================== HARRY POTTER ====================
  hedwig: {
    id: 'hedwig',
    name: 'Cú Tuyết Hedwig',
    species: 'Cú Tuyết Hoàng Gia Hogwarts',
    emoji: '🦉✨',
    avatarBg: 'from-indigo-400 to-sky-500',
    description: 'Cô cú tuyết lông trắng muốt trung thành của Harry Potter, chuyên vận chuyển thư từ và kiến thức uyên thâm.',
    buff: {
      title: 'Thư Cú Hogwarts',
      description: '+25% EXP khi hoàn thành bài Đọc hiểu & Viết luận',
      bonusType: 'exp',
      bonusPercent: 25,
    },
    greetings: [
      'Hoo-hoo! Hedwig mang lá thư từ Hogwarts và danh sách từ mới đến cho bạn nè! 📜',
      'Tiếng vỗ cánh trong đêm lạnh nhắc bạn đừng quên giờ học bài hôm nay!',
      'Hoo! Ánh mắt tuyết trắng của mình luôn theo dõi sự tiến bộ của bạn!',
    ],
    eatSounds: [
      'Hooom! Bánh quy cú thơm phức giòn tan! 🍪',
      'Món ăn thượng hạng của Tháp Cú Hogwarts!',
      'Hoot! Cảm ơn bạn nhỏ tốt bụng của trường Hogwarts!',
    ],
    happyQuotes: [
      'Hedwig cọ chiếc mỏ ấm vào ngón tay bạn âu yếm... 💖',
      'Khả năng đọc hiểu của bạn xứng đáng nhận 100 điểm cho nhà Gryffindor!',
      'Đôi cánh trắng tuyết sẽ luôn che chở và đồng hành cùng bạn!',
    ],
  },
  crookshanks: {
    id: 'crookshanks',
    name: 'Mèo Cam Crookshanks',
    species: 'Mèo Lai Kneazle Thông Thái',
    emoji: '🐱',
    avatarBg: 'from-amber-600 to-orange-500',
    description: 'Mèo cưng mặt tẹt lông xù của Hermione Granger, nửa mèo nửa Kneazle, có trực giác siêu phàm phân biệt đúng sai.',
    buff: {
      title: 'Trực Giác Kneazle',
      description: '+20% Điểm Flashcard & Tốc độ phản xạ từ vựng',
      bonusType: 'speed',
      bonusPercent: 20,
    },
    greetings: [
      'Purrr... Chiếc mũi tẹt này ngửi thấy bạn chưa ôn bài Flashcard đâu nhé! 🐱',
      'Meow! Hermione đã dặn mình phải canh bạn học từ vựng thật kỹ càng!',
      'Mắt vàng óng ánh của mình nhìn thấu mọi lỗi sai phát âm của bạn đấy!',
    ],
    eatSounds: [
      'Cá hồi sốt kem bơ kiểu Pháp ngon tuyệt meow! 🍣',
      'Purr purr... Đĩa ăn sạch bóng loáng!',
      'Măm măm no nê rồi, giờ nằm đè lên sách tiếng Anh ngủ đây!',
    ],
    happyQuotes: [
      'Purrrrrr... Tiếng gừ gừ rung chuyển cả căn phòng vì sướng! 🥰',
      'Bạn thông minh và chăm chỉ chẳng kém gì cô chủ Hermione của mình!',
      'Vuốt ve bộ lông xù này giúp bạn xua tan mọi áp lực thi cử!',
    ],
  },
  fawkes: {
    id: 'fawkes',
    name: 'Phượng Hoàng Fawkes',
    species: 'Phượng Hoàng Lửa Bất Tử Dumbledore',
    emoji: '🦅🔥',
    avatarBg: 'from-red-500 to-amber-500',
    description: 'Loài chim bất tử thiêng liêng của Thầy Dumbledore, nước mắt chữa lành và hồi sinh Streak khi lỡ quên học.',
    buff: {
      title: 'Tái Sinh Từ Tro Tàn',
      description: 'Hồi sinh ngọn lửa Streak khi lỡ quên học & +30% Điểm kiên trì',
      bonusType: 'streak',
      bonusPercent: 30,
    },
    greetings: [
      'Khúc ca phượng hoàng du dương truyền cho bạn lòng dũng cảm vô tận! 🎵✨',
      'Từ đống tro tàn, ngọn lửa tri thức trong bạn sẽ bùng cháy rực rỡ hơn bao giờ hết!',
      'Thầy Dumbledore gửi Fawkes đến để thắp sáng con đường chinh phục tiếng Anh của bạn!',
    ],
    eatSounds: [
      'Tro than hồng và quả mọng đỏ rực lửa ngon tuyệt! 🍒',
      'Lông vũ rực sáng khi được nạp năng lượng tinh khiết!',
      'Tiếng hót trong trẻo vang lên sau bữa ăn thanh đạm!',
    ],
    happyQuotes: [
      'Fawkes xòe đôi cánh vàng đỏ rực rỡ ôm trọn lấy bạn trong hơi ấm kỳ diệu! 🌟',
      'Nước mắt phượng hoàng sẽ xóa tan mọi nỗi sợ sai khi giao tiếp tiếng Anh!',
      'Bạn sở hữu một trái tim kiên cường như ngọn lửa bất diệt!',
    ],
  },

  // ==================== AVENGERS ====================
  goose: {
    id: 'goose',
    name: 'Mèo Vũ Trụ Goose',
    species: 'Quái Thú Flerken Vũ Trụ',
    emoji: '🐈🚀',
    avatarBg: 'from-orange-500 to-indigo-600',
    description: 'Mèo cam đáng yêu của Captain Marvel, thực chất là quái thú Flerken với chiều không gian bỏ túi nuốt trọn từ vựng.',
    buff: {
      title: 'Bao Tử Không Gian',
      description: '+30% EXP & Nuốt trọn mọi từ vựng hóc búa siêu tốc',
      bonusType: 'exp',
      bonusPercent: 30,
    },
    greetings: [
      'Meow! Goose là một bé mèo ngoan... hoặc là một Flerken nuốt cả khối Tesseract! 🌌',
      'Ngoan nào Nick Fury, à nhầm, chào bạn học viên cưng của tớ!',
      'Hôm nay có bài từ vựng nào hóc búa không? Để Goose phóng xúc tu nuốt sạch nhé!',
    ],
    eatSounds: [
      'Gulp! Nuốt trọn cả đĩa thức ăn trong 0.1 giây bằng xúc tu vũ trụ! 🪐',
      'Măm măm... Ngon hơn cả năng lượng đá vô cực!',
      'Meowww! Không gian chiều thứ tư trong bụng đã no 99%!',
    ],
    happyQuotes: [
      'Purr purrr... Goose rất thích được gãi cằm (miễn là đừng làm mù mắt tớ nhé!) 😼',
      'Bạn nuốt từ vựng nhanh ngang ngửa xúc tu Flerken của Goose rồi đấy!',
      'Cùng bay vào vũ trụ bao la với vốn tiếng Anh thượng thừa nào!',
    ],
  },
  rocket: {
    id: 'rocket',
    name: 'Rocket Raccoon',
    species: 'Gấu Mèo Cơ Khí Vũ Trụ',
    emoji: '🦝⚡',
    avatarBg: 'from-amber-700 to-slate-800',
    description: 'Thiên tài vũ khí và cơ khí của Guardians of the Galaxy, chuyên gia phân tích từ vựng IT & Kỹ thuật đỉnh chóp.',
    buff: {
      title: 'Kỹ Sư Công Nghệ Lạc Lối',
      description: '+25% Điểm từ vựng IT, Kỹ thuật số & Sửa lỗi logic',
      bonusType: 'writing',
      bonusPercent: 25,
    },
    greetings: [
      'Đừng có gọi ta là chồn gấu! Ta là kỹ sư vũ khí thiên tài Rocket nghe chưa! 🛠️',
      'Lắp ráp câu tiếng Anh cũng giống như chế tạo khẩu súng plasma vậy, phải chuẩn từng mili!',
      'Cần hack cái bài thi TOEIC kia không? Rocket chế đồ nghề cho nhé!',
    ],
    eatSounds: [
      'Hạt ngũ cốc sấy khô vũ trụ nhai giòn rụm! 🥜',
      'Măm măm! Vừa ăn vừa vặn thêm vài con ốc vít!',
      'Ngon đấy! Cho ta xin thêm cục pin dự phòng tráng miệng coi!',
    ],
    happyQuotes: [
      'Này này... Ai cho xoa đầu... Nhưng mà gãi đúng chỗ ngứa sau tai rồi đấy! 🦝',
      'Khả năng tư duy logic của cậu nhảy số nhanh ngang ngửa tàu Milano rồi!',
      'Cùng nhau cướp trọn điểm 10 tiếng Anh của cả vũ trụ nào!',
    ],
  },
  alligator_loki: {
    id: 'alligator_loki',
    name: 'Cá Sấu Loki Vương Miện',
    species: 'Biến Thể Loki Đa Vũ Trụ',
    emoji: '🐊👑',
    avatarBg: 'from-emerald-700 to-yellow-600',
    description: 'Biến thể cá sấu xanh tinh nghịch của Thần Lừa Lọc Loki đội vương miện sừng vàng, cực mê săn kho báu Coins.',
    buff: {
      title: 'Vận May Thần Lừa Lọc',
      description: '+20% Coins vàng thưởng sau mỗi bài học hoàn thành',
      bonusType: 'coins',
      bonusPercent: 20,
    },
    greetings: [
      'Grrrr... (Chào thần dân tiếng Anh, ta là Loki tối cao đội vương miện sừng vàng!) 👑',
      'Snap! Một cú đớp chuẩn xác là giải quyết xong câu hỏi trắc nghiệm!',
      'Hãy cống nạp từ mới cho vị thần cá sấu này ngay lập tức!',
    ],
    eatSounds: [
      'Chomp! Đớp trọn miếng thịt trong nháy mắt! 🥩',
      'Ngoàm! Hương vị chiến thắng của ngai vàng Asgard!',
      'Grrr nom nom! Bụng cá sấu đã no say!',
    ],
    happyQuotes: [
      'Grrr... (Xoa bụng cá sấu là hành động bày tỏ lòng trung thành xứng đáng!) 🐊💚',
      'Vương miện sừng vàng này phong cho bạn làm Bậc Thầy Giao Tiếp!',
      'Coins vàng của bạn đang tăng lên vùn vụt nhờ sự bảo hộ của Loki!',
    ],
  },

  ice_dragon: {
    id: 'ice_dragon',
    name: 'Rồng Băng Tuyết',
    species: 'Băng Long Cực Bắc',
    emoji: '🐉❄️',
    avatarBg: 'from-cyan-500 to-blue-600',
    description: 'Thần thú rồng băng cổ đại từ đỉnh núi tuyết vĩnh cửu, mang sức mạnh kiểm soát băng giá tuyệt đối.',
    buff: {
      title: 'Hơi Thở Băng Giá',
      description: '+25% Sát thương và phòng thủ trong Đấu Trường Thú Cưng PvP',
      bonusType: 'all',
      bonusPercent: 25,
    },
    greetings: [
      'Roaaar! Băng giá vĩnh cửu đang bảo vệ khu vườn của bạn! ❄️',
      'Đỉnh núi tuyết ngàn năm chúc bạn một ngày học tiếng Anh bùng nổ!',
      'Cùng ta đóng băng mọi câu hỏi ngữ pháp hóc búa nào! 🐉',
    ],
    eatSounds: [
      'Măm măm tinh thể băng ngọt lành! 🍧',
      'Hơi lạnh sảng khoái lan tỏa khắp cơ thể!',
      'Gầm vang! Năng lượng băng đăng đã phục hồi 100%!',
    ],
    happyQuotes: [
      'Cảm giác được vuốt ve ấm áp xua tan cái lạnh giá băng! 💖',
      'Bạn là kỵ sĩ rồng xuất sắc nhất trên đỉnh tuyết phủ!',
      'Sức mạnh băng long sẽ luôn song hành cùng bạn!',
    ],
  },

  // ==================== DORAEMON ====================
  doraemon: {
    id: 'doraemon',
    name: 'Mèo Máy Doraemon',
    species: 'Mèo Máy Thế Kỷ 22',
    emoji: '🐱🔔',
    avatarBg: 'from-blue-500 to-sky-400',
    description: 'Chú mèo máy tương lai không tai với chiếc túi thần kỳ 4 chiều, sở hữu Bánh mì trí nhớ và Cửa thần kỳ.',
    buff: {
      title: 'Túi Bảo Bối Thần Kỳ',
      description: 'Mở khóa bảo bối học tập: +30% EXP & Coins toàn diện mọi kỹ năng',
      bonusType: 'all',
      bonusPercent: 30,
    },
    greetings: [
      'Tèn ten ten ten! Doraemon có Bánh Mì Trí Nhớ giúp bạn nuốt trọn từ vựng nè! 🍞✨',
      'Nobita ơi học bài đi... À bạn là bạn học chăm chỉ của mình mà, cùng mở sách nào!',
      'Gặp bài khó cứ để Doraemon thò tay vào túi thần kỳ tìm bảo bối nhé!',
    ],
    eatSounds: [
      'Bánh Rán Dorayaki nhân đậu đỏ ngọt lịm ngon mê ly! 🥞',
      'Măm măm! Hạnh phúc nhất trên đời là được ăn bánh rán cùng bạn!',
      'Ngon tuyệt cú mèo máy! Doraemon tràn đầy pin rồi!',
    ],
    happyQuotes: [
      'Bạn tốt bụng và siêng năng hơn Nobita gấp một triệu lần luôn! 💙',
      'Xoa cái đầu tròn xoe của Doraemon là bài kiểm tra tiếng Anh điểm 10 chắc chắn!',
      'Cánh cửa thần kỳ sẽ đưa bạn bay đến bất kỳ đất nước nào bạn muốn!',
    ],
  },
  dorami: {
    id: 'dorami',
    name: 'Mèo Máy Dorami',
    species: 'Em Gái Mèo Máy Chu Đáo',
    emoji: '🎀',
    avatarBg: 'from-yellow-400 to-amber-500',
    description: 'Cô em gái mèo máy vàng thông minh tinh tế với chiếc nơ đỏ xinh xắn, luôn ngăn nắp và điểm số xuất sắc.',
    buff: {
      title: 'Bộ Não Siêu Việt Thế Kỷ 22',
      description: '+25% Điểm ngữ pháp & Tối ưu thời gian làm bài chính xác',
      bonusType: 'writing',
      bonusPercent: 25,
    },
    greetings: [
      'Chào bạn! Dorami đã chuẩn bị sẵn thời khóa biểu học tiếng Anh siêu hiệu quả rồi nè! 🎀',
      'Anh Doraemon hay đãng trí lắm, để Dorami kèm bạn học ngữ pháp thật bài bản nhé!',
      'Mỗi ngày dành 15 phút học tập nghiêm túc là bạn sẽ tiến bộ vượt bậc!',
    ],
    eatSounds: [
      'Bánh quy dưa lưới ngọt mát thơm lừng! 🍈',
      'Trà chiều thanh đạm và bánh kem thơm ngon!',
      'Dorami no bụng rồi, cảm ơn bạn rất chu đáo!',
    ],
    happyQuotes: [
      'Được bạn yêu quý Dorami vui quá đi! Chiếc nơ đỏ đang reo vui nè! 🎀✨',
      'Bài làm của bạn vừa sạch đẹp vừa chuẩn ngữ pháp, đáng khen lắm!',
      'Cứ kiên trì theo kế hoạch, Dorami tin bạn sẽ thành tài!',
    ],
  },

  // ==================== KIRBY ====================
  kirby: {
    id: 'kirby',
    name: 'Kirby Hồng Tròn Xoe',
    species: 'Chiến Binh Sao Dream Land',
    emoji: '🌸⭐',
    avatarBg: 'from-pink-400 to-rose-500',
    description: 'Sinh vật tròn xoe màu hồng đến từ Dream Land, năng lực hút trọn mọi kiến thức và sao lấp lánh ban tặng niềm vui.',
    buff: {
      title: 'Hút Sao Kiến Thức',
      description: '+30% Coins & EXP thưởng sau mọi thử thách phản xạ',
      bonusType: 'exp',
      bonusPercent: 30,
    },
    greetings: [
      'Poyo poyo! Kirby chào bạn! Hôm nay chúng mình cùng bay trên Ngôi Sao Hiệp Sĩ nhé! ⭐',
      'Poyooo! Kirby há miệng hút trọn cuốn từ điển tiếng Anh cho bạn nè! 📖✨',
      'Cùng nhảy múa điệu Kirby Dance ăn mừng thành tích học tập nào!',
    ],
    eatSounds: [
      'HÚTTTTT! Nuốt trọn quả táo và bánh dâu tây trong 1 giây! Poyo! 🍓',
      'Poyo nom nom! Bụng Kirby tròn xoe bay bổng như bong bóng!',
      'Ngon quá chừng! Kirby biến hình thành Kirby Học Giả!',
    ],
    happyQuotes: [
      'Poyooo! Bụng mềm như kẹo dẻo của Kirby được bạn ôm thích ghê! 🥰',
      'Những ngôi sao may mắn đang rơi quanh bạn lấp lánh tuyệt đẹp!',
      'Poyo poyo! Bạn là người bạn ngọt ngào nhất của Dream Land! 💖',
    ],
  },
};

export const SHOP_ITEMS: ShopItem[] = [
  // --- MŨ & NÓN ---
  {
    id: 'grad_cap',
    name: 'Mũ Cử Nhân Tri Thức',
    type: 'hat',
    categoryLabel: '🎓 Nón & Mũ',
    price: 80,
    emoji: '🎓',
    description: 'Biểu tượng tốt nghiệp xuất sắc khóa giao tiếp thực chiến.',
    benefit: '+5% EXP cho thú cưng',
  },
  {
    id: 'wizard_hat',
    name: 'Nón Phù Thủy Ngữ Pháp',
    type: 'hat',
    categoryLabel: '🎓 Nón & Mũ',
    price: 120,
    emoji: '🧙‍♂️',
    description: 'Nón phép thuật giúp biến hóa câu văn mượt mà và lưu loát.',
    benefit: '+10% EXP cho thú cưng',
  },
  {
    id: 'royal_crown',
    name: 'Vương Miện Hoàng Kim',
    type: 'hat',
    categoryLabel: '🎓 Nón & Mũ',
    price: 200,
    emoji: '👑',
    description: 'Vương miện lấp lánh dành riêng cho bậc thầy ngôn ngữ.',
    benefit: 'Tăng vẻ quý phái và +15% EXP',
  },
  {
    id: 'gamer_headset',
    name: 'Tai Nghe DJ Developer',
    type: 'hat',
    categoryLabel: '🎓 Nón & Mũ',
    price: 100,
    emoji: '🎧',
    description: 'Tai nghe gaming RGB chống ồn giúp thú cưng nghe rõ từng âm tiết.',
    benefit: 'Tăng điểm luyện nghe',
  },
  {
    id: 'cool_cap',
    name: 'Mũ Lưỡi Trai Streetwear',
    type: 'hat',
    categoryLabel: '🎓 Nón & Mũ',
    price: 60,
    emoji: '🧢',
    description: 'Phong cách dạo phố trẻ trung năng động.',
    benefit: 'Thú cưng trông cực ngầu',
  },
  {
    id: 'farmer_straw_hat',
    name: 'Nón Rơm Nông Dân Cổ Điển',
    type: 'hat',
    categoryLabel: '🎓 Nón & Mũ',
    price: 50,
    emoji: '👒',
    description: 'Chiếc nón rơm đồng quê cổ điển che nắng che mưa khi chăm sóc nông trại.',
    benefit: 'Che nắng che mưa khi làm vườn',
  },
  {
    id: 'luffy_straw_hat',
    name: 'Mũ Rơm Hải Tặc Luffy',
    type: 'hat',
    categoryLabel: '🎓 Nón & Mũ',
    price: 150,
    emoji: '👒',
    description: 'Mũ rơm dải ruy băng đỏ của Vua Hải Tặc One Piece, khơi dậy tinh thần tự do chinh phục đại dương tiếng Anh.',
    benefit: '+15% Tinh thần phiêu lưu & EXP',
  },
  {
    id: 'konoha_headband',
    name: 'Băng Đô Nhẫn Giả Konoha',
    type: 'hat',
    categoryLabel: '🎓 Nón & Mũ',
    price: 140,
    emoji: '🍃',
    description: 'Băng trán kim loại khắc biểu tượng Làng Lá Naruto, biểu trưng cho ý chí Lửa bất diệt không bao giờ bỏ cuộc.',
    benefit: '+15% Kiên trì & Chống gãy Streak',
  },
  {
    id: 'sorting_hat',
    name: 'Mũ Phân Loại Hogwarts',
    type: 'hat',
    categoryLabel: '🎓 Nón & Mũ',
    price: 160,
    emoji: '🧙‍♂️',
    description: 'Chiếc nón phân loại phép thuật ngàn năm tuổi của Harry Potter, nhìn thấu tiềm năng ngôn ngữ của học viên.',
    benefit: '+20% Điểm Ngữ Pháp & EXP',
  },
  {
    id: 'ironman_mask',
    name: 'Mặt Nạ Người Sắt Nano',
    type: 'hat',
    categoryLabel: '🎓 Nón & Mũ',
    price: 180,
    emoji: '🤖',
    description: 'Mũ giáp Titanium vàng đỏ tích hợp HUD Jarvis quét phân tích phát âm bản xứ với độ chính xác tuyệt đối.',
    benefit: '+20% Độ chính xác AI Voice',
  },
  {
    id: 'bamboo_copter',
    name: 'Chong Chóng Tre Thần Kỳ',
    type: 'hat',
    categoryLabel: '🎓 Nón & Mũ',
    price: 130,
    emoji: '🚁',
    description: 'Bảo bối thế kỷ 22 trứ danh của Doraemon, gắn lên đầu giúp bé bay lượn vi vu vượt qua mọi bài tập khó.',
    benefit: '+15% Tốc độ phản xạ giao tiếp',
  },
  {
    id: 'kirby_star_crown',
    name: 'Vương Miện Sao Kirby',
    type: 'hat',
    categoryLabel: '🎓 Nón & Mũ',
    price: 170,
    emoji: '👑',
    description: 'Vương miện ngôi sao rực rỡ xứ sở Dream Land Kirby, hút trọn kho từ vựng tiếng Anh như một cơn lốc.',
    benefit: '+15% Khả năng ghi nhớ từ mới',
  },
  {
    id: 'cowboy_hat',
    name: 'Mũ Cao Bồi Miền Tây',
    type: 'hat',
    categoryLabel: '🎓 Nón & Mũ',
    price: 110,
    emoji: '🤠',
    description: 'Nón da cao bồi viễn tây bụi bặm phong trần, luyện phát âm chuẩn giọng Anh - Mỹ hào sảng.',
    benefit: '+10% Chuẩn giọng American Accent',
  },
  {
    id: 'astronaut_helmet',
    name: 'Mũ Phi Hành Gia Vũ Trụ',
    type: 'hat',
    categoryLabel: '🎓 Nón & Mũ',
    price: 190,
    emoji: '👨‍🚀',
    description: 'Mũ bảo hiểm thám hiểm không gian với kính phản quang mạ vàng, cùng bạn vươn tới những vì sao tri thức.',
    benefit: '+20% Coins & EXP bài học khó',
  },
  {
    id: 'bear_beanie',
    name: 'Mũ Tai Gấu Ấm Áp',
    type: 'hat',
    categoryLabel: '🎓 Nón & Mũ',
    price: 95,
    emoji: '🐻',
    description: 'Chiếc mũ len dệt hai tai gấu tròn xoe mềm mịn, giữ ấm cho thú cưng trong những đêm cày cuốc từ vựng.',
    benefit: 'Tăng 10% Hạnh phúc & Giảm mệt mỏi',
  },
  {
    id: 'pikachu_cap',
    name: 'Mũ Tai Vàng Điện Quang',
    type: 'hat',
    categoryLabel: '🎓 Nón & Mũ',
    price: 135,
    emoji: '⚡',
    description: 'Mũ lưỡi trai có hai tai sét Pokémon vàng óng phóng 100.000 Volts nạp đầy hứng khởi học tập tức thì.',
    benefit: '+15% Tốc độ làm bài Flashcard',
  },

  // --- QUẦN ÁO & TRANG PHỤC ---
  {
    id: 'dev_hoodie',
    name: 'Áo Hoodie Dev Hacker',
    type: 'outfit',
    categoryLabel: '👕 Trang Phục',
    price: 150,
    emoji: '💻',
    description: 'Chiếc áo hoodie công nghệ xanh emerald đậm chất IT Engineer.',
    benefit: '+10% Coins thưởng khi học từ vựng IT',
  },
  {
    id: 'farmer_overalls',
    name: 'Quần Yếm Bác Nông Dân',
    type: 'outfit',
    categoryLabel: '👕 Trang Phục',
    price: 120,
    emoji: '👖',
    description: 'Quần yếm bò nông nghiệp chuyên dụng cuốc đất tưới rau năng động.',
    benefit: '+10% Coins thưởng khi chăm sóc thú cưng',
  },
  {
    id: 'business_suit',
    name: 'Vest Doanh Nhân TOEIC',
    type: 'outfit',
    categoryLabel: '👕 Trang Phục',
    price: 180,
    emoji: '👔',
    description: 'Bộ âu phục lịch lãm, chuyên nghiệp cho mọi cuộc đàm phán quốc tế.',
    benefit: '+15% Coins thưởng khi học TOEIC',
  },
  {
    id: 'master_gi',
    name: 'Võ Phục Karate Đai Đen',
    type: 'outfit',
    categoryLabel: '👕 Trang Phục',
    price: 160,
    emoji: '🥋',
    description: 'Võ phục của sự kỷ luật thép, không bao giờ ngắt quãng streak.',
    benefit: 'Tăng khả năng giữ vững streak',
  },
  {
    id: 'cozy_scarf',
    name: 'Khăn Quàng Len Mùa Đông',
    type: 'outfit',
    categoryLabel: '👕 Trang Phục',
    price: 90,
    emoji: '🧣',
    description: 'Khăn len dệt ấm áp giữ ấm cổ họng cho thú cưng luyện phát âm.',
    benefit: 'Tăng điểm giọng nói Voice AI',
  },
  {
    id: 'akatsuki_cloak',
    name: 'Áo Choàng Mây Đỏ Akatsuki',
    type: 'outfit',
    categoryLabel: '👕 Trang Phục',
    price: 220,
    emoji: '🖤',
    description: 'Áo choàng đen thêu họa tiết mây đỏ huyền bí, thần thái ngút ngàn của tổ chức nhẫn giả tinh anh Naruto.',
    benefit: '+20% Thưởng EXP & Uy lực giao tiếp',
  },
  {
    id: 'gryffindor_robe',
    name: 'Áo Chùng Phù Thủy Gryffindor',
    type: 'outfit',
    categoryLabel: '👕 Trang Phục',
    price: 210,
    emoji: '✨',
    description: 'Áo chùng đỏ thẫm viền vàng thêu phù hiệu sư tử dũng cảm của nhà Gryffindor Harry Potter.',
    benefit: '+15% EXP & Khí chất dũng cảm',
  },
  {
    id: 'stark_nano_armor',
    name: 'Bộ Giáp Công Nghệ Stark',
    type: 'outfit',
    categoryLabel: '👕 Trang Phục',
    price: 250,
    emoji: '🛡️',
    description: 'Áo giáp hạt nano đỏ vàng tích hợp lò phản ứng hồ quang Arc trước ngực, bứt phá năng suất học tập.',
    benefit: '+25% Coins khi làm bài tập IT',
  },
  {
    id: 'doraemon_pocket',
    name: 'Túi Thần Kỳ 4 Chiều Doraemon',
    type: 'outfit',
    categoryLabel: '👕 Trang Phục',
    price: 200,
    emoji: '🎒',
    description: 'Chiếc túi bán nguyệt màu trắng không gian 4 chiều trước bụng, chứa đựng cả kho bảo bối tiếng Anh vô tận.',
    benefit: '+20% Giảm giá đồ shop & +10% EXP',
  },
  {
    id: 'festival_kimono',
    name: 'Áo Kimono Lễ Hội Nhật Bản',
    type: 'outfit',
    categoryLabel: '👕 Trang Phục',
    price: 180,
    emoji: '👘',
    description: 'Trang phục truyền thống Nhật Bản dệt hoa văn hoa anh đào tinh xảo, diện đi lễ hội ngắm pháo hoa rực rỡ.',
    benefit: '+15% Điểm Hạnh phúc & Giao tiếp',
  },
  {
    id: 'helloworld_tshirt',
    name: 'Áo Thun Developer "Hello World"',
    type: 'outfit',
    categoryLabel: '👕 Trang Phục',
    price: 110,
    emoji: '💻',
    description: 'Chiếc áo thun đen in dòng code console.log("Hello World!"); kinh điển của mọi lập trình viên.',
    benefit: '+10% Coins thưởng khi học từ vựng IT',
  },
  {
    id: 'super_saiyan_gi',
    name: 'Võ Phục Siêu Saiyan Quy Lão',
    type: 'outfit',
    categoryLabel: '👕 Trang Phục',
    price: 230,
    emoji: '🥋',
    description: 'Võ phục màu cam viền xanh chữ Quy huyền thoại của Songoku, đánh thức tiềm năng bứt phá mọi giới hạn.',
    benefit: '+25% Sức mạnh Streak & Bứt phá',
  },
  {
    id: 'detective_trenchcoat',
    name: 'Áo Măng Tô Thám Tử Conan',
    type: 'outfit',
    categoryLabel: '👕 Trang Phục',
    price: 195,
    emoji: '🕵️‍♂️',
    description: 'Áo khoác dài màu be kèm nơ đỏ biến âm, giúp tìm ra "chân lý ngữ pháp duy nhất" trong các bài thi khó.',
    benefit: '+15% Độ chính xác khi làm trắc nghiệm',
  },

  // --- PHỤ KIỆN & TRANG SỨC ---
  {
    id: 'smart_glasses',
    name: 'Kính Mắt Trí Tuệ',
    type: 'accessory',
    categoryLabel: '👓 Phụ Kiện',
    price: 70,
    emoji: '👓',
    description: 'Kính gọng tròn bác học nhìn thấu cấu trúc ngữ pháp phức tạp.',
    benefit: 'Tăng 5% chỉ số Hạnh phúc',
  },
  {
    id: 'sunglasses',
    name: 'Kính Râm Siêu Ngầu',
    type: 'accessory',
    categoryLabel: '👓 Phụ Kiện',
    price: 70,
    emoji: '🕶️',
    description: 'Kính râm đen sành điệu tỏa sáng như ngôi sao giao tiếp.',
    benefit: 'Thú cưng luôn rạng rỡ',
  },
  {
    id: 'golden_bell',
    name: 'Chuông Vàng May Mắn',
    type: 'accessory',
    categoryLabel: '👓 Phụ Kiện',
    price: 90,
    emoji: '🔔',
    description: 'Vòng cổ chuông vàng ngân vang mỗi khi phát âm chuẩn xác.',
    benefit: 'Kêu leng keng vui tai khi click',
  },
  {
    id: 'angel_wings',
    name: 'Cánh Thiên Thần Tinh Khôi',
    type: 'accessory',
    categoryLabel: '👓 Phụ Kiện',
    price: 250,
    emoji: '🪽',
    description: 'Đôi cánh phát sáng dịu dàng bảo hộ cho học viên.',
    benefit: 'Hiệu ứng phát sáng lấp lánh',
  },
  {
    id: 'elder_wand',
    name: 'Đũa Phép Cơm Nguội Elder Wand',
    type: 'accessory',
    categoryLabel: '👓 Phụ Kiện',
    price: 260,
    emoji: '🪄',
    description: 'Cây đũa phép vô địch trong Tam Bảo Tử Thần Harry Potter, thi triển câu cú tiếng Anh chuẩn xác mê hoặc người nghe.',
    benefit: '+25% EXP & Điểm viết luận',
  },
  {
    id: 'vibranium_shield',
    name: 'Khiên Ngôi Sao Vibranium',
    type: 'accessory',
    categoryLabel: '👓 Phụ Kiện',
    price: 240,
    emoji: '🛡️',
    description: 'Chiếc khiên hợp kim Vibranium không thể phá hủy của Captain America, bảo hộ chuỗi Streak trước mọi sơ suất.',
    benefit: 'Bảo hộ Streak & +15% Coins',
  },
  {
    id: 'doraemon_bell',
    name: 'Chuông Vàng Doraemon Đeo Cổ',
    type: 'accessory',
    categoryLabel: '👓 Phụ Kiện',
    price: 120,
    emoji: '🔔',
    description: 'Chiếc chuông vàng nhỏ xinh trên dải ruy băng đỏ quanh cổ, phát tiếng leng keng gọi bạn bè cùng học.',
    benefit: 'Leng keng vui nhộn & +10% Hạnh phúc',
  },
  {
    id: 'demon_wings',
    name: 'Cánh Dơi Hắc Ám Dark Wings',
    type: 'accessory',
    categoryLabel: '👓 Phụ Kiện',
    price: 250,
    emoji: '🦇',
    description: 'Đôi cánh dơi bóng đêm thần bí phong cách anime gothic, tỏa hào quang hắc ám mỗi khi sải bước.',
    benefit: '+20% Uy lực bứt phá & Tốc độ',
  },
  {
    id: 'rgb_gaming_headset',
    name: 'Tai Nghe Gaming RGB Vòm 7.1',
    type: 'accessory',
    categoryLabel: '👓 Phụ Kiện',
    price: 130,
    emoji: '🎧',
    description: 'Tai nghe over-ear âm thanh vòm 7.1 tích hợp dải LED Rainbow, lọc sạch tạp âm để luyện nghe TOEIC/IELTS cực nét.',
    benefit: '+20% Điểm nghe Listening',
  },
  {
    id: 'zoro_bamboo_sword',
    name: 'Kiếm Gỗ Rèn Luyện Zoro',
    type: 'accessory',
    categoryLabel: '👓 Phụ Kiện',
    price: 175,
    emoji: '🗡️',
    description: 'Thanh kiếm gỗ katana của kiếm sĩ Zoro One Piece, chém bay mọi cấu trúc ngữ pháp phức tạp chỉ trong một chiêu.',
    benefit: '+15% Tốc độ giải bài tập',
  },
  {
    id: 'pokeball_pendant',
    name: 'Dây Chuyền Quả Cầu Pokéball',
    type: 'accessory',
    categoryLabel: '👓 Phụ Kiện',
    price: 140,
    emoji: '🔴',
    description: 'Mặt dây chuyền quả cầu bắt thú Pokémon huyền thoại, nhắc nhở học viên "bắt trọn" từng từ mới mỗi ngày.',
    benefit: '+15% Tỷ lệ ghi nhớ từ vựng',
  },
  {
    id: 'infinity_gauntlet',
    name: 'Găng Tay Vô Cực Khảm Đá Quý',
    type: 'accessory',
    categoryLabel: '👓 Phụ Kiện',
    price: 300,
    emoji: '🧤',
    description: 'Găng tay mạ vàng đính đủ 6 viên đá vô cực Thanos, búng tay một cái là thuộc làu 50 từ vựng hóc búa.',
    benefit: '+30% EXP & Toàn bộ chỉ số',
  },
  {
    id: 'flame_ninja_scarf',
    name: 'Khăn Rằn Ninja Phong Hỏa',
    type: 'accessory',
    categoryLabel: '👓 Phụ Kiện',
    price: 110,
    emoji: '🧣',
    description: 'Khăn quàng đỏ rực bay phấp phới trong gió lốc, tăng khí chất của một nhẫn giả tiếng Anh thực thụ.',
    benefit: 'Hiệu ứng bay trong gió cực ngầu',
  },
  {
    id: 'fairy_wand',
    name: 'Gậy Phép Thủy Thủ Mặt Trăng',
    type: 'accessory',
    categoryLabel: '👓 Phụ Kiện',
    price: 180,
    emoji: '🌙',
    description: 'Gậy phép đính trăng khuyết và nơ hồng: "Nhân danh tình yêu và công lý, ta sẽ chinh phục tiếng Anh bản xứ!"',
    benefit: '+15% Tự tin khi phát âm Voice AI',
  },

  // --- CẢNH QUAN KHU VƯỜN (HABITATS) ---
  {
    id: 'emerald_garden',
    name: 'Vườn Sinh Thái Xanh Mát',
    type: 'habitat',
    categoryLabel: '🏡 Cảnh Quan Vườn',
    price: 0,
    emoji: '🌿',
    description: 'Đồng cỏ xanh tươi ngọc bích, bướm bay dập dờn và nắng sớm ấm áp.',
    benefit: 'Cảnh quan mặc định thanh bình',
  },
  {
    id: 'cozy_den',
    name: 'Căn Phòng IT Developer',
    type: 'habitat',
    categoryLabel: '🏡 Cảnh Quan Vườn',
    price: 150,
    emoji: '🖥️',
    description: 'Phòng làm việc công nghệ ấm cúng, đèn LED RGB và giá sách IT.',
    benefit: 'Không gian lý tưởng cho dân Tech',
  },
  {
    id: 'sunset_beach',
    name: 'Bãi Biển Nhiệt Đới',
    type: 'habitat',
    categoryLabel: '🏡 Cảnh Quan Vườn',
    price: 200,
    emoji: '🏖️',
    description: 'Bờ cát vàng óng ả, hàng dừa rợp bóng và tiếng sóng biển rì rào.',
    benefit: 'Xua tan mọi căng thẳng học tập',
  },
  {
    id: 'sky_castle',
    name: 'Lâu Đài Mây Huyền Ảo',
    type: 'habitat',
    categoryLabel: '🏡 Cảnh Quan Vườn',
    price: 300,
    emoji: '🏰',
    description: 'Cung điện bồng bềnh giữa mây ngũ sắc và cầu vồng rực rỡ.',
    benefit: 'Cảnh quan tối thượng danh giá',
  },
  {
    id: 'thousand_sunny',
    name: 'Boong Tàu Hải Tặc Sunny',
    type: 'habitat',
    categoryLabel: '🏡 Cảnh Quan Vườn',
    price: 250,
    emoji: '🏴‍☠️',
    description: 'Đầu sư tử Sunny rạng rỡ, cột buồm hiên ngang đón gió, rương vàng châu báu và đại dương xanh ngát.',
    benefit: '+15% Coins & Tinh thần phiêu lưu Grand Line',
  },
  {
    id: 'konoha_valley',
    name: 'Thung Lũng Nhẫn Giả Làng Lá',
    type: 'habitat',
    categoryLabel: '🏡 Cảnh Quan Vườn',
    price: 260,
    emoji: '🍃',
    description: 'Vách đá chạm khắc tượng Hokage, suối Onsen nước nóng bốc hơi, rừng trúc thanh tịnh và quán mì Ichiraku thơm phức.',
    benefit: '+15% Phản xạ giao tiếp & Ý chí của Lửa',
  },
  {
    id: 'hogwarts_hall',
    name: 'Đại Sảnh Đường Hogwarts',
    type: 'habitat',
    categoryLabel: '🏡 Cảnh Quan Vườn',
    price: 280,
    emoji: '⚡',
    description: 'Hàng trăm ngọn nến ma thuật lơ lửng, cửa sổ kính màu Gothic, lò sưởi bập bùng và bàn tiệc pháp thuật thịnh soạn.',
    benefit: '+20% EXP Ngữ Pháp Phép Thuật',
  },
  {
    id: 'doraemon_field',
    name: 'Bãi Đất Trống Doraemon',
    type: 'habitat',
    categoryLabel: '🏡 Cảnh Quan Vườn',
    price: 180,
    emoji: '🔔',
    description: '3 ống cống bê tông tròn kinh điển xếp chồng, hàng rào gỗ mộc mạc, Cánh Cửa Thần Kỳ và bầu trời tuổi thơ thanh bình.',
    benefit: 'Ký ức tuổi thơ ấm áp, giảm 25% tốc độ đói',
  },
  {
    id: 'dream_land',
    name: 'Vương Quốc Giấc Mơ Kirby',
    type: 'habitat',
    categoryLabel: '🏡 Cảnh Quan Vườn',
    price: 280,
    emoji: '⭐',
    description: 'Cây kẹo mút khổng lồ bảy sắc, Ngôi Sao Vàng Warp Star, dòng suối cầu vồng kẹo ngọt và mưa sao băng lấp lánh.',
    benefit: '+20% Hạnh phúc & Năng lượng bứt phá',
  },

  // --- ĐỒ ĂN & DINH DƯỠNG (FOODS) ---
  {
    id: 'green_apple',
    name: 'Táo Xanh Tươi Mát',
    type: 'food',
    categoryLabel: '🍏 Thức Ăn',
    price: 10,
    emoji: '🍏',
    description: 'Quả táo rừng mọng nước giàu vitamin trí não.',
    hungerBoost: 20,
    happinessBoost: 10,
    energyBoost: 10,
    expBoost: 5,
  },
  {
    id: 'dev_burger',
    name: 'Hamburger IT Nạp Năng Lượng',
    type: 'food',
    categoryLabel: '🍏 Thức Ăn',
    price: 25,
    emoji: '🍔',
    description: 'Bữa ăn thịnh soạn đầy đủ dinh dưỡng sau những giờ cày cuốc.',
    hungerBoost: 40,
    happinessBoost: 20,
    energyBoost: 25,
    expBoost: 15,
  },
  {
    id: 'sweet_carrot',
    name: 'Cà Rốt Tươi Giòn',
    type: 'food',
    categoryLabel: '🍏 Thức Ăn',
    price: 15,
    emoji: '🥕',
    description: 'Củ cà rốt cam giòn ngọt giúp mắt sáng tinh anh.',
    hungerBoost: 25,
    happinessBoost: 15,
    energyBoost: 15,
    expBoost: 8,
  },
  {
    id: 'coding_coffee',
    name: 'Cà Phê Espresso Coding',
    type: 'food',
    categoryLabel: '🍏 Thức Ăn',
    price: 20,
    emoji: '☕',
    description: 'Tách cà phê đậm đà giúp thú cưng tỉnh táo 100% năng lượng.',
    hungerBoost: 10,
    energyBoost: 45,
    happinessBoost: 15,
    expBoost: 10,
  },
  {
    id: 'lucky_cookie',
    name: 'Bánh Quy May Mắn',
    type: 'food',
    categoryLabel: '🍏 Thức Ăn',
    price: 20,
    emoji: '🍪',
    description: 'Chiếc bánh nướng thơm lừng bên trong có lời chúc thành công.',
    hungerBoost: 15,
    happinessBoost: 35,
    energyBoost: 15,
    expBoost: 12,
  },
  {
    id: 'dorayaki_pancake',
    name: 'Bánh Rán Dorayaki Khoái Khẩu',
    type: 'food',
    categoryLabel: '🍏 Thức Ăn',
    price: 30,
    emoji: '🥞',
    description: 'Món bánh rán kẹp nhân đậu đỏ ngọt lịm thơm phức mà chú mèo máy Doraemon mê tít, nạp đầy niềm vui.',
    hungerBoost: 45,
    happinessBoost: 35,
    energyBoost: 25,
    expBoost: 18,
  },
  {
    id: 'ichiraku_ramen',
    name: 'Tô Mì Ramen Ichiraku Bốc Khói',
    type: 'food',
    categoryLabel: '🍏 Thức Ăn',
    price: 40,
    emoji: '🍜',
    description: 'Bát ramen thịt xá xíu, trứng lòng đào và chả cá Naruto thơm nức mũi trứ danh làng Lá, nạp đầy Chakra học tập.',
    hungerBoost: 60,
    happinessBoost: 40,
    energyBoost: 35,
    expBoost: 25,
  },
  {
    id: 'onepiece_roast_meat',
    name: 'Đùi Thịt Nướng Khổng Lồ One Piece',
    type: 'food',
    categoryLabel: '🍏 Thức Ăn',
    price: 45,
    emoji: '🍖',
    description: 'Đùi thịt nướng tẩm ướp sốt barbecue thơm lừng kích thước siêu to của Luffy, ăn vào hồi phục 100% sinh lực.',
    hungerBoost: 75,
    happinessBoost: 30,
    energyBoost: 50,
    expBoost: 20,
  },
  {
    id: 'bertie_bott_beans',
    name: 'Kẹo Đậu Đủ Vị Bertie Bott',
    type: 'food',
    categoryLabel: '🍏 Thức Ăn',
    price: 25,
    emoji: '🍬',
    description: 'Hộp kẹo phép thuật trứ danh thế giới Harry Potter với đủ vị bất ngờ từ sô-cô-la ngọt ngào đến bạc hà sảng khoái.',
    hungerBoost: 20,
    happinessBoost: 50,
    energyBoost: 25,
    expBoost: 22,
  },
  {
    id: 'kirby_max_tomato',
    name: 'Cà Chua Hồi Máu Max Tomato',
    type: 'food',
    categoryLabel: '🍏 Thức Ăn',
    price: 35,
    emoji: '🍅',
    description: 'Quả cà chua thần kỳ in chữ M của chú bé Kirby xứ Dream Land, hồi phục ngay lập tức thanh no nê và thể lực.',
    hungerBoost: 70,
    happinessBoost: 45,
    energyBoost: 60,
    expBoost: 20,
  },
  {
    id: 'boba_milk_tea',
    name: 'Trà Sữa Trân Châu Đường Đen',
    type: 'food',
    categoryLabel: '🍏 Thức Ăn',
    price: 28,
    emoji: '🧋',
    description: 'Ly trà sữa béo ngậy cùng trân châu dai giòn sần sật và lớp kem cheese bồng bềnh, xua tan mọi mệt mỏi ôn bài.',
    hungerBoost: 30,
    happinessBoost: 55,
    energyBoost: 30,
    expBoost: 16,
  },
  {
    id: 'cheese_pizza',
    name: 'Bánh Pizza Phô Mai Kéo Sợi',
    type: 'food',
    categoryLabel: '🍏 Thức Ăn',
    price: 38,
    emoji: '🍕',
    description: 'Miếng pizza nướng lò củi vàng ươm ngập tràn phô mai Mozzarella béo ngậy kéo sợi dài tít tắp, ăn là ghiền.',
    hungerBoost: 65,
    happinessBoost: 35,
    energyBoost: 30,
    expBoost: 18,
  },
  {
    id: 'redbean_taiyaki',
    name: 'Bánh Cá Nướng Taiyaki Đậu Đỏ',
    type: 'food',
    categoryLabel: '🍏 Thức Ăn',
    price: 22,
    emoji: '🐟',
    description: 'Chiếc bánh hình chú cá tráp vàng ruộm giòn tan ngoài vỏ, mềm mịn ngọt bùi nhân đậu đỏ Azuki Nhật Bản.',
    hungerBoost: 35,
    happinessBoost: 30,
    energyBoost: 20,
    expBoost: 14,
  },
  {
    id: 'salmon_sushi',
    name: 'Đĩa Sushi Cá Hồi Tươi Rói',
    type: 'food',
    categoryLabel: '🍏 Thức Ăn',
    price: 32,
    emoji: '🍣',
    description: 'Những miếng cơm cuộn cá hồi tươi óng ả chấm wasabi cay nồng, giàu Omega-3 giúp trí não phát triển vượt bậc.',
    hungerBoost: 40,
    happinessBoost: 35,
    energyBoost: 35,
    expBoost: 20,
  },

  // --- ĐỒ TRANG TRÍ VƯỜN (DECORATIONS) ---
  {
    id: 'magic_tree',
    name: 'Cây Táo Thần EXP',
    type: 'decor',
    categoryLabel: '🌳 Đồ Trang Trí',
    price: 120,
    emoji: '🌳',
    description: 'Cây cổ thụ thần kỳ tỏa bóng mát cho khu vườn.',
    benefit: 'Điểm nhấn xanh tươi cho khu vườn',
  },
  {
    id: 'crystal_fountain',
    name: 'Đài Phun Nước Pha Lê',
    type: 'decor',
    categoryLabel: '🌳 Đồ Trang Trí',
    price: 160,
    emoji: '⛲',
    description: 'Đài phun nước mát lành với những tia nước lấp lánh cầu vồng.',
    benefit: 'Âm thanh róc rách thư giãn',
  },
  {
    id: 'picnic_tent',
    name: 'Lều Trại Dã Ngoại',
    type: 'decor',
    categoryLabel: '🌳 Đồ Trang Trí',
    price: 140,
    emoji: '⛺',
    description: 'Chiếc lều ấm áp nơi thú cưng ngả lưng nghỉ ngơi.',
    benefit: 'Không gian cắm trại vui vẻ',
  },
  {
    id: 'magic_lantern',
    name: 'Đèn Lồng Lung Linh',
    type: 'decor',
    categoryLabel: '🌳 Đồ Trang Trí',
    price: 100,
    emoji: '🏮',
    description: 'Đèn lồng phương Đông tỏa ánh sáng vàng ấm áp ban đêm.',
    benefit: 'Thắp sáng ấm cúng',
  },
  {
    id: 'flower_bed',
    name: 'Thảm Hoa Cúc Vàng',
    type: 'decor',
    categoryLabel: '🌳 Đồ Trang Trí',
    price: 80,
    emoji: '🌸',
    description: 'Vạt hoa nở rộ ngát hương thu hút đàn bướm dạo chơi.',
    benefit: 'Tô điểm sắc màu rực rỡ',
  },
  {
    id: 'hokage_monument',
    name: 'Tượng Hokage Đá Danh Dự',
    type: 'decor',
    categoryLabel: '🌳 Đồ Trang Trí',
    price: 260,
    emoji: '🗿',
    description: 'Vách đá tạc chân dung các vị Hokage bảo vệ ngôi làng Naruto, tôn vinh tinh thần lãnh đạo và kiên cường.',
    benefit: 'Điểm nhấn phong thủy uy nghiêm',
  },
  {
    id: 'pirate_treasure_chest',
    name: 'Hòm Rương Kho Báu Vàng Bạc',
    type: 'decor',
    categoryLabel: '🌳 Đồ Trang Trí',
    price: 220,
    emoji: '🪙',
    description: 'Rương gỗ viền đồng nạm đá quý mở hé lộ hàng nghìn đồng tiền vàng One Piece lấp lánh rực rỡ.',
    benefit: 'Hào quang phú quý & May mắn Coins',
  },
  {
    id: 'magic_snowglobe',
    name: 'Quả Cầu Tuyết Ma Thuật Hogwarts',
    type: 'decor',
    categoryLabel: '🌳 Đồ Trang Trí',
    price: 190,
    emoji: '🔮',
    description: 'Quả cầu thủy tinh chứa lâu đài phép thuật thu nhỏ, mỗi khi lắc nhẹ những hạt tuyết kim tuyến lại bay lượn.',
    benefit: 'Tỏa ánh sáng kỳ ảo ban đêm',
  },
  {
    id: 'totoro_bus_stop',
    name: 'Biển Báo Bến Xe Buýt Totoro',
    type: 'decor',
    categoryLabel: '🌳 Đồ Trang Trí',
    price: 180,
    emoji: '🚏',
    description: 'Biển dừng xe buýt mộc mạc bên bìa rừng Ghibli, nơi chú mèo Totoro cầm ô đứng chờ chuyến xe buýt mèo.',
    benefit: 'Khung cảnh tuổi thơ êm đềm ấm áp',
  },
  {
    id: 'cherry_blossom_tree',
    name: 'Cây Anh Đào Nở Hoa Rực Rỡ',
    type: 'decor',
    categoryLabel: '🌳 Đồ Trang Trí',
    price: 210,
    emoji: '🌸',
    description: 'Cây hoa anh đào Nhật Bản bung nở tán hồng rực rỡ, cánh hoa bay lãng mạn nhẹ rơi theo làn gió xuân.',
    benefit: 'Cánh hoa rơi bồng bềnh thơ mộng',
  },
  {
    id: 'torii_gate',
    name: 'Cổng Đền Torii Đỏ Truyền Thống',
    type: 'decor',
    categoryLabel: '🌳 Đồ Trang Trí',
    price: 230,
    emoji: '⛩️',
    description: 'Cổng Torii sơn đỏ son thanh tịnh mở ra cánh cổng kết nối tâm hồn bình yên và sự tập trung trí tuệ cao độ.',
    benefit: 'Không gian trang nghiêm & Thanh tịnh',
  },
  {
    id: 'mini_ufo_sculpture',
    name: 'Đĩa Bay Mini UFO Không Gian',
    type: 'decor',
    categoryLabel: '🌳 Đồ Trang Trí',
    price: 240,
    emoji: '🛸',
    description: 'Mô hình đĩa bay viễn tưởng bay lơ lửng bằng từ trường, chiếu chùm sáng neon huyền bí xuống thảm cỏ.',
    benefit: 'Hiệu ứng lơ lửng công nghệ cao',
  },
  {
    id: 'japanese_tea_table',
    name: 'Bàn Trà Đạo Tatami Nhật Bản',
    type: 'decor',
    categoryLabel: '🌳 Đồ Trang Trí',
    price: 170,
    emoji: '🍵',
    description: 'Bàn gỗ trà đạo mộc mạc cùng đệm ngồi êm ái và ấm trà xanh Matcha thơm ngát giúp tâm tĩnh như nước.',
    benefit: 'Tăng điểm tĩnh tâm & Thư giãn',
  },
];

// Titles based on pet level
export function getPetTitle(level: number): string {
  if (level >= 30) return '👑 Thần Thú Bảo Hộ';
  if (level >= 20) return '🌟 Đại Sư Giao Tiếp';
  if (level >= 12) return '⚔️ Chiến Binh Ngữ Pháp';
  if (level >= 5) return '📖 Học Giả Tri Thức';
  return '🌱 Thú Cưng Tập Sự';
}
